table Orders
	lineageTag: 3a9fffdb-d2f7-42e8-a770-1aae2c2ba02e

	measure 'Orders Sum of Sales' = SUM('Orders'[Sales])
		lineageTag: 4e50f6a8-300e-4424-96ce-6eb7fed29d29

	measure 'Total Sales' = SUM('Orders'[Sales])
		formatString: $#,0
		lineageTag: b0958891-dd44-4d42-8a4e-09bc27132517

	measure 'Total Profit' = SUM('Orders'[Profit])
		formatString: $#,0
		lineageTag: c73dea40-ced4-4c4d-b30e-72029ff483ae

	measure 'Profit Ratio' = DIVIDE([Total Profit],[Total Sales])
		formatString: 0.0%
		lineageTag: 9e9290a5-bec0-49bf-84e9-236cca8732ba

	measure 'Profit per Order' = DIVIDE([Total Profit], DISTINCTCOUNT('Orders'[Order ID]))
		formatString: $#,0.00
		lineageTag: 3ff681e6-4ad8-4aaf-9c29-51bd0007356b

	measure 'Sales per Customer' = DIVIDE([Total Sales], DISTINCTCOUNT('Orders'[Customer Name]))
		formatString: $#,0.00
		lineageTag: fb95b623-ec8a-45a1-8d11-8bc2f9842b03

	measure 'Avg Discount' = AVERAGE('Orders'[Discount])
		formatString: 0.0%
		lineageTag: cf200c3e-6ae7-44f7-a6b3-a9b4696e0b11

	column Category
		dataType: string
		lineageTag: 89ac0175-2577-4062-a173-0cc72f79a067
		summarizeBy: none
		sourceColumn: Category

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a368dae3-dcd6-4544-a3ee-6ad724afa6ce
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: 0e421aad-8673-4a01-92ac-48bd4213df2b
			defaultHierarchy: LocalDateTable_a420ff36-3206-4997-b8a9-5db8d75b4819.'Date Hierarchy'

		annotation UnderlyingDateTimeDataType = Date

	column Segment
		dataType: string
		lineageTag: 297028b3-4d95-4dd9-a4d0-7aabc5ca9ae4
		summarizeBy: none
		sourceColumn: Segment

	column Region
		dataType: string
		lineageTag: e6b6b1bb-0ad0-4389-a21d-6a1849168416
		summarizeBy: none
		sourceColumn: Region

	column State/Province
		dataType: string
		lineageTag: 96022f2f-7dbf-4683-9d99-f6f4a3f37930
		summarizeBy: none
		sourceColumn: State/Province

	column 'Customer Name'
		dataType: string
		lineageTag: 32c99e78-4937-4d08-bec6-b1c351fad08b
		summarizeBy: none
		sourceColumn: Customer Name

	column Profit
		dataType: double
		lineageTag: 0471c07a-1176-48d2-a28b-8b8e1418385c
		summarizeBy: sum
		sourceColumn: Profit

	column Quantity
		dataType: int64
		lineageTag: 48424ae9-d114-4f22-9e47-be0a5666d344
		summarizeBy: sum
		sourceColumn: Quantity

	column Sales
		dataType: double
		lineageTag: b0fece9b-f5b1-442e-a185-ac89d8a6fa4d
		summarizeBy: sum
		sourceColumn: Sales

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: bc2f94c0-02f2-46e7-b02a-66d6944ddc53
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: 43602857-be7f-4eb3-a6f0-933388d437fb
			defaultHierarchy: LocalDateTable_3d14f7f4-07f1-41b8-9448-94a8f44c1a53.'Date Hierarchy'

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: f3e2b713-6afc-4c0e-9a62-395b306f694e
		summarizeBy: none
		sourceColumn: Ship Mode

	column 'Order ID'
		dataType: string
		lineageTag: 55f2303f-7257-42a5-83ed-3a169604b8a8
		summarizeBy: none
		sourceColumn: Order ID

	column 'Product Name'
		dataType: string
		lineageTag: deb36621-7673-49e9-a3cb-9541336491bc
		summarizeBy: none
		sourceColumn: Product Name

	column City
		dataType: string
		lineageTag: 81e3024f-7d9c-4256-a9f5-19a996a4d6ea
		summarizeBy: none
		sourceColumn: City

	column Discount
		dataType: double
		lineageTag: 87c9a3b1-2246-41c5-a79e-02713136f802
		summarizeBy: sum
		sourceColumn: Discount

	column 'Postal Code'
		dataType: string
		lineageTag: f5406e9b-b7fd-4bed-b677-736a076083a1
		summarizeBy: none
		sourceColumn: Postal Code

	column Sub-Category
		dataType: string
		lineageTag: 52f03e58-f74e-4219-92fd-27fe038bcc28
		summarizeBy: none
		sourceColumn: Sub-Category

	column Country/Region
		dataType: string
		lineageTag: 1f3f9fbd-e73e-4a5c-b518-7471ee9ebbc0
		summarizeBy: none
		sourceColumn: Country/Region

	column 'Order Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 00000000-0000-0000-0000-000000000002
		summarizeBy: none
		sourceColumn: Order Month

		variation Variation
			isDefault
			relationship: 5d74642f-6c31-4305-81c3-c1edffe69593
			defaultHierarchy: LocalDateTable_d25cef6f-43c4-468d-a481-0231b421f5f1.'Date Hierarchy'

		annotation UnderlyingDateTimeDataType = Date

	column Profitability
		dataType: string
		lineageTag: 00000000-0000-0000-0000-000000000003
		summarizeBy: none
		sourceColumn: Profitability

	column 'Row ID'
		dataType: string
		lineageTag: 9b73d62b-47f3-4e81-81a1-75ed994db6ab
		summarizeBy: none
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 90c6c2c4-7606-4784-bffe-df56fa3f5ff6
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 32b33365-9c2a-44d1-97c7-fb76f3d56a22
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	partition FullData = m
		mode: import
		source =
				let
					Source = Excel.Workbook(File.Contents("C:\Users\Pooja Satija\Downloads\tab-pbip-31-code-new-visuals\tab-pbip-31-code-new-visuals\SuperstorePBIP\Data\Superstore\Sample - Superstore.xls"), null, true),
					OrdersTable = try Source{[Item="Orders",Kind="Table"]}[Data] otherwise null,
					OrdersSheet = try Source{[Item="Orders",Kind="Sheet"]}[Data] otherwise null,
					Selected = if OrdersTable <> null then OrdersTable else if OrdersSheet <> null then OrdersSheet else Source{0}[Data],
					Promoted = Table.PromoteHeaders(Selected, [PromoteAllScalars=true]),
					ChangedType = Table.TransformColumnTypes(Promoted, {{"Order Date", type date}, {"Ship Date", type date}, {"Sales", type number}, {"Profit", type number}, {"Discount", type number}, {"Quantity", Int64.Type}}),
					CleanNumbers = Table.TransformColumns(ChangedType, {{"Sales", each try Number.From(_) otherwise null, type number}, {"Profit", each try Number.From(_) otherwise null, type number}, {"Discount", each try Number.From(_) otherwise null, type number}, {"Quantity", each try Number.From(_) otherwise null, Int64.Type}}),
					AddedMonth = Table.AddColumn(CleanNumbers, "Order Month", each Date.StartOfMonth([Order Date]), type date),
					AddedProfitability = Table.AddColumn(AddedMonth, "Profitability", each if [Profit] >= 0 then "Profitable" else "Unprofitable", type text)
					in
					AddedProfitability

	annotation PBI_ResultType = Table

