model Model
	culture: en-US
	defaultPowerBIDataSourceVersion: powerBI_V3
	sourceQueryCulture: en-IN
	dataAccessOptions
		legacyRedirects
		returnErrorValuesAsNull

annotation __PBI_TimeIntelligenceEnabled = 1

annotation PBI_ProTooling = ["DevMode"]

ref cultureInfo en-US

table 'Sales Commission'
	column 'Sales Person'
		dataType: string
	column 'Calculation_4120925132203686'
		dataType: string
	column 'Sales'
		dataType: int64
	measure 'Sum of Sales' = SUM('Sales Commission'[Sales])

	partition 'FullData'
		mode: import
		source =
			let
			            Source = #table(type table [Sales Person = text, Calculation_4120925132203686 = text, Sales = number], {})
			        in
			            Source
table 'Orders'
	column 'Category'
		dataType: string
	column 'Profit'
		dataType: double
	column 'Customer Name'
		dataType: string
	column 'Sales'
		dataType: double
	column 'Region'
		dataType: string
	column 'Order ID'
		dataType: string
	column 'Segment'
		dataType: string
	column 'Order Date'
		dataType: dateTime
	column '__tableau_internal_object_id__'
		dataType: string
	column 'Product Name'
		dataType: string
	measure 'Sum of Profit' = SUM('Orders'[Profit])
	measure 'Sum of Sales' = SUM('Orders'[Sales])
	partition 'FullData'
		mode: import
		source =
			let
			            Source = #table(type table [Category = text, Profit = number, Customer Name = text, Sales = number, Region = text, Order ID = text, Segment = text, Order Date = datetime, __tableau_internal_object_id__ = text, Product Name = text], {})
			        in
			            Source
