table Orders
	lineageTag: a4242067-c9a5-4e08-a523-6237dc6d3627

	measure 'Orders Sum of Sales' = SUM('Orders'[Sales])
		lineageTag: ea304806-12ec-44e2-bd8f-3bfd3175b7bf

	measure 'Total Sales' = SUM('Orders'[Sales])
		formatString: $#,0
		lineageTag: 7e140f36-6669-45c8-bd05-95907fd58d2b

	measure 'Total Profit' = SUM('Orders'[Profit])
		formatString: $#,0
		lineageTag: 5575cbb6-19c2-4455-92e4-d84e9ae4e656

	measure 'Profit Ratio' = DIVIDE(SUM('Orders'[Profit]), SUM('Orders'[Sales]))
		formatString: 0.0%
		lineageTag: 029865b4-1d54-4a6d-8300-0a6ab202baf3

	measure 'Profit per Order' = DIVIDE(SUM('Orders'[Profit]), DISTINCTCOUNT('Orders'[Order ID]))
		formatString: $#,0.00
		lineageTag: 71328ec5-7dd8-4fcd-8535-46db90fcd3f0

	measure 'Sales per Customer' = DIVIDE(SUM('Orders'[Sales]), DISTINCTCOUNT('Orders'[Customer Name]))
		formatString: $#,0.00
		lineageTag: 1e8f86d7-cb9c-4377-855d-d55f71cf3601

	measure 'Avg Discount' = AVERAGE('Orders'[Discount])
		formatString: 0.0%
		lineageTag: 2fad7952-799c-4f48-bb2e-87ea3167cb21

	column Category
		dataType: string
		lineageTag: d7125b24-d383-41b2-91d3-857edefd55fa
		summarizeBy: none
		sourceColumn: Category

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5eb7a2c4-e433-4558-87c3-5110a6228803
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: bbeeb81f-b90f-4ccf-ba4a-b252a2409c6a
			defaultHierarchy: LocalDateTable_9202b1b2-a281-4dd9-a1a7-2b4b1306e124.'Date Hierarchy'

		annotation UnderlyingDateTimeDataType = Date

	column Segment
		dataType: string
		lineageTag: 9863743f-e225-441e-b139-577e33192547
		summarizeBy: none
		sourceColumn: Segment

	column Region
		dataType: string
		lineageTag: 87366c7e-afef-4aa7-9205-32274e126dc0
		summarizeBy: none
		sourceColumn: Region

	column State/Province
		dataType: string
		lineageTag: 078d285b-d15f-4e2d-b607-b62b4ce1733a
		summarizeBy: none
		sourceColumn: State/Province

	column 'Customer Name'
		dataType: string
		lineageTag: dc7f078d-2b04-4521-974a-875895deedf9
		summarizeBy: none
		sourceColumn: Customer Name

	column Profit
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: d9ac71b9-6c98-4b74-bd32-d98f59691c1c
		summarizeBy: sum
		sourceColumn: Profit

	column Quantity
		dataType: int64
		lineageTag: ce903df4-875a-46c4-a0f5-ab8b1ea24b2a
		summarizeBy: sum
		sourceColumn: Quantity

	column Sales
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f3a2fb40-3986-4a55-9c03-f08ea8908911
		summarizeBy: sum
		sourceColumn: Sales

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 47524377-7d00-4c8f-9a64-495b9bb28497
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: 1c76f1ba-0ea7-4e69-b2c3-381a9d36dbe9
			defaultHierarchy: LocalDateTable_7d66fb0c-40a3-4439-8a9a-e4c5c08a1663.'Date Hierarchy'

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: 258c864a-a88c-4e68-9382-23ffaecebb62
		summarizeBy: none
		sourceColumn: Ship Mode

	column 'Order ID'
		dataType: string
		lineageTag: e6cfda1d-042e-41da-95a1-be1e57e3a288
		summarizeBy: none
		sourceColumn: Order ID

	column 'Product Name'
		dataType: string
		lineageTag: 72f88a40-3e50-44dc-a895-4d9c7b417c68
		summarizeBy: none
		sourceColumn: Product Name

	column City
		dataType: string
		lineageTag: 30faebe6-c92e-44a1-8ecd-3eae3133d06f
		summarizeBy: none
		sourceColumn: City

	column Discount
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c1a3543a-0be0-4b23-948b-3a16c601c8db
		summarizeBy: sum
		sourceColumn: Discount

	column 'Postal Code'
		dataType: string
		lineageTag: 4583b409-e070-446b-afba-cb5056e56403
		summarizeBy: none
		sourceColumn: Postal Code

	column Sub-Category
		dataType: string
		lineageTag: 027b3e3b-12e2-460b-bfde-655cdda49d82
		summarizeBy: none
		sourceColumn: Sub-Category

	column Country/Region
		dataType: string
		lineageTag: 767b4c32-a054-44ec-ac29-8ec88f61e974
		summarizeBy: none
		sourceColumn: Country/Region

	column 'Order Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 51188087-2b11-44d4-91aa-da1e7349a10b
		summarizeBy: none
		sourceColumn: Order Month

		variation Variation
			isDefault
			relationship: b50dec0d-4eed-4670-b591-0d71f7536b89
			defaultHierarchy: LocalDateTable_6116e850-ea7b-4d8c-b642-c69ef7fde37c.'Date Hierarchy'

		annotation UnderlyingDateTimeDataType = Date

	column Profitability
		dataType: string
		lineageTag: 69b0d1c5-d4ae-476a-8829-bba2624d1b33
		summarizeBy: none
		sourceColumn: Profitability

	column 'Row ID'
		dataType: string
		lineageTag: a2d4285a-3e31-4919-bfd4-b43e5cd581a7
		summarizeBy: none
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 49fb5dc2-20cc-46d2-be88-37d67db7e9f2
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 7aff379b-aac3-4617-bdef-764b331895cf
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	partition FullData = m
		mode: import
		source =
				let
				Source = Excel.Workbook(File.Contents("C:\Users\Pooja Satija\Downloads\tab-pbip-31-code-new-visuals\tab-pbip-31-code-new-visuals\SuperstorePBIP\Data\Superstore\Sample - Superstore.xls"), null, true),
					OrdersTable = try Source{[Item="Orders",Kind="Table"]}[Data] otherwise null,
					OrdersSheet = try Source{[Item="Orders",Kind="Sheet"]}[Data] otherwise null,
					Selected = if OrdersTable <> null then OrdersTable else if OrdersSheet <> null then OrdersSheet else Source{0}[Data],
					Promoted = Table.PromoteHeaders(Selected, [PromoteAllScalars=true]),
					ChangedType = Table.TransformColumnTypes(Promoted, {{"Order Date", type date}, {"Ship Date", type date}, {"Sales", type number}, {"Profit", type number}, {"Discount", type number}, {"Quantity", Int64.Type}}),
					CleanNumbers = Table.TransformColumns(ChangedType, {{"Sales", each try Number.From(_) otherwise null, type number}, {"Profit", each try Number.From(_) otherwise null, type number}, {"Discount", each try Number.From(_) otherwise null, type number}, {"Quantity", each try Number.From(_) otherwise null, Int64.Type}}),
					AddedMonth = Table.AddColumn(CleanNumbers, "Order Month", each Date.StartOfMonth([Order Date]), type date),
					OrderProfit = Table.Group(AddedMonth, {"Order ID"}, {{"Order Profit", each List.Sum([Profit]), type number}}),
					Merged = Table.NestedJoin(AddedMonth, {"Order ID"}, OrderProfit, {"Order ID"}, "OrderProfit", JoinKind.LeftOuter),
					Expanded = Table.ExpandTableColumn(Merged, "OrderProfit", {"Order Profit"}, {"Order Profit"}),
					AddedProfitability = Table.AddColumn(Expanded, "Profitability", each if [Order Profit] >= 0 then "Profitable" else "Unprofitable", type text),
					RemovedOrderProfit = Table.RemoveColumns(AddedProfitability, {"Order Profit"})
					in
					RemovedOrderProfit

	annotation PBI_ResultType = Table

