table Parameters
	lineageTag: ac3800e1-2fed-4706-9a59-f19cb98abc59

	column 'Parameter 1'
		dataType: double
		summarizeBy: sum
		sourceColumn: Parameter 1
		lineageTag: 0e280645-fc90-49ab-bdb2-b93fa2720a7d

	column 'Parameter 2'
		dataType: double
		summarizeBy: sum
		sourceColumn: Parameter 2
		lineageTag: a0ba31c4-c46e-49ff-814a-4667d16e8153

	column 'Base Salary'
		dataType: int64
		summarizeBy: sum
		sourceColumn: Base Salary
		lineageTag: 6f982c5c-0039-4cb6-ba70-6e7cc05b5ac7

	column 'Commission Rate'
		dataType: double
		summarizeBy: sum
		sourceColumn: Commission Rate
		lineageTag: 36b1c928-1360-41b3-a8fe-a4c828add988

	column 'New Quota'
		dataType: int64
		summarizeBy: sum
		sourceColumn: New Quota
		lineageTag: 7edb3acd-706f-4d55-ad6e-12b09072939a

	column 'Parameter 1 1'
		dataType: string
		summarizeBy: none
		sourceColumn: Parameter 1 1
		lineageTag: 3c879d0d-c12d-4e71-8f5c-532fee87e9c3

	partition FullData = m
		mode: import
		source =
			let
				Source = Excel.Workbook(File.Contents("C:\Users\Pooja Satija\Downloads\tab-pbip-31-code-new-visuals\tab-pbip-31-code-new-visuals\SuperstorePBIP\Data\Superstore\\Sample - Superstore.xls"), null, true),
				OrdersTable = try Source{[Item="Orders",Kind="Table"]}[Data] otherwise null,
				OrdersSheet = try Source{[Item="Orders",Kind="Sheet"]}[Data] otherwise null,
				Selected = if OrdersTable <> null then OrdersTable else if OrdersSheet <> null then OrdersSheet else Source{0}[Data],
				Promoted = Table.PromoteHeaders(Selected, [PromoteAllScalars=true]),
				ChangedType = Table.TransformColumnTypes(Promoted, {{"Order Date", type date}, {"Ship Date", type date}, {"Sales", type number}, {"Profit", type number}, {"Discount", type number}, {"Quantity", Int64.Type}}),
				CleanNumbers = Table.TransformColumns(ChangedType, {{"Sales", each try Number.From(_) otherwise null, type number}, {"Profit", each try Number.From(_) otherwise null, type number}, {"Discount", each try Number.From(_) otherwise null, type number}, {"Quantity", each try Number.From(_) otherwise null, Int64.Type}})
			in
				CleanNumbers
	annotation PBI_ResultType = Table

