table Parameters
	lineageTag: 75cb0cd4-925e-452b-84f7-83856686750d

	column 'Parameter 1'
		dataType: double
		summarizeBy: sum
		sourceColumn: Parameter 1
		lineageTag: 93e6a788-8b92-49d0-bc05-86be5bb300c6

	column 'Parameter 2'
		dataType: double
		summarizeBy: sum
		sourceColumn: Parameter 2
		lineageTag: 693b9e8c-84ba-4f16-9fdd-bfc30cf95518

	column 'Base Salary'
		dataType: int64
		summarizeBy: sum
		sourceColumn: Base Salary
		lineageTag: de1eaa7e-643e-405a-bf09-c7eb4a71ba24

	column 'Commission Rate'
		dataType: double
		summarizeBy: sum
		sourceColumn: Commission Rate
		lineageTag: 44df6f8b-76c1-4783-9067-7347513f9e5d

	column 'New Quota'
		dataType: int64
		summarizeBy: sum
		sourceColumn: New Quota
		lineageTag: 1a42f32f-ef7e-4467-95af-5522bc3f2f8b

	column 'Parameter 1 1'
		dataType: string
		summarizeBy: none
		sourceColumn: Parameter 1 1
		lineageTag: ed8487bf-50c6-4c0c-9269-c5e944c28955

	partition FullData = m
		mode: import
		source =
			let
				Source = Excel.Workbook(File.Contents("C:\Users\Pooja Satija\Downloads\tab-pbip-31-code-new-visuals\tab-pbip-31-code-new-visuals\SuperstorePBIP\Data\Superstore\\Sample - Superstore.xls"), null, true),
				OrdersTable = try Source{[Item="Orders",Kind="Table"]}[Data] otherwise null,
				OrdersSheet = try Source{[Item="Orders",Kind="Sheet"]}[Data] otherwise null,
				Selected = if OrdersTable <> null then OrdersTable else if OrdersSheet <> null then OrdersSheet else Source{0}[Data],
				Promoted = Table.PromoteHeaders(Selected, [PromoteAllScalars=true]),
				ChangedType = Table.TransformColumnTypes(Promoted, {{"Order Date", type date}, {"Ship Date", type date}, {"Sales", type number}, {"Profit", type number}, {"Discount", type number}, {"Quantity", Int64.Type}}),
				CleanNumbers = Table.TransformColumns(ChangedType, {{"Sales", each try Number.From(_) otherwise null, type number}, {"Profit", each try Number.From(_) otherwise null, type number}, {"Discount", each try Number.From(_) otherwise null, type number}, {"Quantity", each try Number.From(_) otherwise null, Int64.Type}}),
				AddedMonth = Table.AddColumn(CleanNumbers, "Order Month", each Date.StartOfMonth([Order Date]), type date),
				AddedProfitability = Table.AddColumn(AddedMonth, "Profitability", each if [Profit] >= 0 then "Profitable" else "Unprofitable", type text),
				AddedYear = Table.AddColumn(AddedProfitability, "Order Year", each Date.Year([Order Date]), Int64.Type),
				AddedDaysToShipActual = Table.AddColumn(AddedYear, "Days to Ship Actual", each Duration.Days([Ship Date] - [Order Date]), Int64.Type),
				AddedDaysToShipScheduled = Table.AddColumn(AddedDaysToShipActual, "Days to Ship Scheduled", each if [Ship Mode] = "Same Day" then 0 else if [Ship Mode] = "First Class" then 1 else if [Ship Mode] = "Second Class" then 3 else if [Ship Mode] = "Standard Class" then 6 else null, Int64.Type)
			in
				AddedDaysToShipScheduled
	annotation PBI_ResultType = Table

