table Parameters
	lineageTag: 1edc3818-b9b4-4b36-8b99-5469e2e29c56

	column 'Parameter 1'
		dataType: double
		summarizeBy: sum
		sourceColumn: Parameter 1
		lineageTag: 24a880f7-37f0-496d-a794-05d7b9f95920

	column 'Parameter 2'
		dataType: double
		summarizeBy: sum
		sourceColumn: Parameter 2
		lineageTag: 666776f3-e192-4acd-b386-7f26610bf6ef

	column 'Base Salary'
		dataType: int64
		summarizeBy: sum
		sourceColumn: Base Salary
		lineageTag: 14330010-6e15-4ccc-8728-5f8c617eab0b

	column 'Commission Rate'
		dataType: double
		summarizeBy: sum
		sourceColumn: Commission Rate
		lineageTag: a5fed113-416a-4f40-b5bf-a8dd7166c61c

	column 'New Quota'
		dataType: int64
		summarizeBy: sum
		sourceColumn: New Quota
		lineageTag: 5e6933ce-e48b-4dd4-8a5b-5a4c20d7b9d8

	column 'Parameter 1 1'
		dataType: string
		summarizeBy: none
		sourceColumn: Parameter 1 1
		lineageTag: de2d6036-2c6b-4c23-92b7-2118c6c0bab7

	partition FullData = m
		mode: import
		source =
			let
				Source = Excel.Workbook(File.Contents("C:\Users\Pooja Satija\Downloads\tab-pbip-31-code-new-visuals\tab-pbip-31-code-new-visuals\SuperstorePBIP\Data\Superstore\\Sample - Superstore.xls"), null, true),
				OrdersTable = try Source{[Item="Orders",Kind="Table"]}[Data] otherwise null,
				OrdersSheet = try Source{[Item="Orders",Kind="Sheet"]}[Data] otherwise null,
				Selected = if OrdersTable <> null then OrdersTable else if OrdersSheet <> null then OrdersSheet else Source{0}[Data],
				Promoted = Table.PromoteHeaders(Selected, [PromoteAllScalars=true]),
				ChangedType = Table.TransformColumnTypes(Promoted, {{"Order Date", type date}, {"Ship Date", type date}, {"Sales", type number}, {"Profit", type number}, {"Discount", type number}, {"Quantity", Int64.Type}}),
				CleanNumbers = Table.TransformColumns(ChangedType, {{"Sales", each try Number.From(_) otherwise null, type number}, {"Profit", each try Number.From(_) otherwise null, type number}, {"Discount", each try Number.From(_) otherwise null, type number}, {"Quantity", each try Number.From(_) otherwise null, Int64.Type}}),
				AddedMonth = Table.AddColumn(CleanNumbers, "Order Month", each Date.StartOfMonth([Order Date]), type date),
				AddedProfitability = Table.AddColumn(AddedMonth, "Profitability", each if [Profit] >= 0 then "Profitable" else "Unprofitable", type text),
				AddedYear = Table.AddColumn(AddedProfitability, "Order Year", each Date.Year([Order Date]), Int64.Type)
			in
				AddedYear
	annotation PBI_ResultType = Table

