table Parameters
	lineageTag: 5039f379-a66a-428a-9ff9-86221e22de83

	column 'Parameter 1'
		dataType: double
		summarizeBy: sum
		sourceColumn: Parameter 1
		lineageTag: e91c6bbd-6590-41d1-bb41-17b5afb14905

	column 'Parameter 2'
		dataType: double
		summarizeBy: sum
		sourceColumn: Parameter 2
		lineageTag: 95672a57-a528-428c-9e08-92fc78ab5b06

	column 'Base Salary'
		dataType: int64
		summarizeBy: sum
		sourceColumn: Base Salary
		lineageTag: 77267a01-b6c4-4a38-bbf5-0821ec5a6e07

	column 'Commission Rate'
		dataType: double
		summarizeBy: sum
		sourceColumn: Commission Rate
		lineageTag: 3ca8016d-8bd9-49b4-aaca-5b9d37480cba

	column 'New Quota'
		dataType: int64
		summarizeBy: sum
		sourceColumn: New Quota
		lineageTag: 54ff316d-c132-400d-9e7e-262c83dcb6d3

	column 'Parameter 1 1'
		dataType: string
		summarizeBy: none
		sourceColumn: Parameter 1 1
		lineageTag: ab7c2c4e-98ee-452c-bf07-5d9974199a24

	partition FullData = m
		mode: import
		source =
			let
				Source = Excel.Workbook(File.Contents("C:\Users\Pooja Satija\Downloads\tab-pbip-31-code-new-visuals\tab-pbip-31-code-new-visuals\SuperstorePBIP\Data\Superstore\\Sample - Superstore.xls"), null, true),
				OrdersTable = try Source{[Item="Orders",Kind="Table"]}[Data] otherwise null,
				OrdersSheet = try Source{[Item="Orders",Kind="Sheet"]}[Data] otherwise null,
				Selected = if OrdersTable <> null then OrdersTable else if OrdersSheet <> null then OrdersSheet else Source{0}[Data],
				Promoted = Table.PromoteHeaders(Selected, [PromoteAllScalars=true]),
				ChangedType = Table.TransformColumnTypes(Promoted, {{"Order Date", type date}, {"Ship Date", type date}, {"Sales", type number}, {"Profit", type number}, {"Discount", type number}, {"Quantity", Int64.Type}}),
				CleanNumbers = Table.TransformColumns(ChangedType, {{"Sales", each try Number.From(_) otherwise null, type number}, {"Profit", each try Number.From(_) otherwise null, type number}, {"Discount", each try Number.From(_) otherwise null, type number}, {"Quantity", each try Number.From(_) otherwise null, Int64.Type}})
			in
				CleanNumbers
	annotation PBI_ResultType = Table

