table Parameters
	lineageTag: 871605c4-8919-4e1f-bd50-401f4677cf5b

	column 'Parameter 1'
		dataType: double
		summarizeBy: sum
		sourceColumn: Parameter 1
		lineageTag: cff7ac07-78e7-4f0d-84e8-8e382fb27898

	column 'Parameter 2'
		dataType: double
		summarizeBy: sum
		sourceColumn: Parameter 2
		lineageTag: c1117fd9-8dd7-47a6-9c05-ad3d40dc6294

	column 'Base Salary'
		dataType: int64
		summarizeBy: sum
		sourceColumn: Base Salary
		lineageTag: 545b0e8b-f401-470c-a952-1ea2645ec37d

	column 'Commission Rate'
		dataType: double
		summarizeBy: sum
		sourceColumn: Commission Rate
		lineageTag: 9f06cda9-18b5-42d1-b2bf-c376122e6509

	column 'New Quota'
		dataType: int64
		summarizeBy: sum
		sourceColumn: New Quota
		lineageTag: 09926b36-7df2-470c-a3a6-3c35c5abf461

	column 'Parameter 1 1'
		dataType: string
		summarizeBy: none
		sourceColumn: Parameter 1 1
		lineageTag: 51845eda-eae5-41f0-99dd-2c51b6f1e744

	partition FullData = m
		mode: import
		source =
			let
				Source = Excel.Workbook(File.Contents("C:\Users\Pooja Satija\Downloads\tab-pbip-31-code-new-visuals\tab-pbip-31-code-new-visuals\SuperstorePBIP\Data\Superstore\\Sample - Superstore.xls"), null, true),
				OrdersTable = try Source{[Item="Orders",Kind="Table"]}[Data] otherwise null,
				OrdersSheet = try Source{[Item="Orders",Kind="Sheet"]}[Data] otherwise null,
				Selected = if OrdersTable <> null then OrdersTable else if OrdersSheet <> null then OrdersSheet else Source{0}[Data],
				Promoted = Table.PromoteHeaders(Selected, [PromoteAllScalars=true]),
				ChangedType = Table.TransformColumnTypes(Promoted, {{"Order Date", type date}, {"Ship Date", type date}, {"Sales", type number}, {"Profit", type number}, {"Discount", type number}, {"Quantity", Int64.Type}}),
				CleanNumbers = Table.TransformColumns(ChangedType, {{"Sales", each try Number.From(_) otherwise null, type number}, {"Profit", each try Number.From(_) otherwise null, type number}, {"Discount", each try Number.From(_) otherwise null, type number}, {"Quantity", each try Number.From(_) otherwise null, Int64.Type}}),
				AddedMonth = Table.AddColumn(CleanNumbers, "Order Month", each Date.StartOfMonth([Order Date]), type date),
				AddedProfitability = Table.AddColumn(AddedMonth, "Profitability", each if [Profit] >= 0 then "Profitable" else "Unprofitable", type text),
				AddedYear = Table.AddColumn(AddedProfitability, "Order Year", each Date.Year([Order Date]), Int64.Type)
			in
				AddedYear
	annotation PBI_ResultType = Table

