table 'Sample - Superstore'
	lineageTag: 5dca6d05-2ec7-4987-9c8a-2649131550dd

	column Category
		dataType: string
		summarizeBy: none
		sourceColumn: Category
		lineageTag: 93bec2aa-0347-4b0d-9044-572eee63aba3

	column 'Order Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Order Date
		lineageTag: f3b99669-c11b-499a-9322-aa51b83d64a6

	column Segment
		dataType: string
		summarizeBy: none
		sourceColumn: Segment
		lineageTag: ac23f00e-f04b-459f-8ce2-698ae62db57d

	column Region
		dataType: string
		summarizeBy: none
		sourceColumn: Region
		lineageTag: 042d6ae2-ee01-4842-afd8-d05e02185910

	column 'State/Province'
		dataType: string
		summarizeBy: none
		sourceColumn: State/Province
		lineageTag: 9219f2cd-7c3c-4da6-b5ab-2c63f74b5b67

	column Calculation_0831103151444568
		dataType: int64
		summarizeBy: sum
		sourceColumn: Calculation_0831103151444568
		lineageTag: 9012ae16-f8c1-4669-a509-d3838f2cfa1d

	column Calculation_6861103170623145
		dataType: int64
		summarizeBy: sum
		sourceColumn: Calculation_6861103170623145
		lineageTag: 8c361e33-4066-4414-806d-0401629ac10d

	column Calculation_9321103144526191
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9321103144526191
		lineageTag: 49ce9d22-f485-42f5-b99c-5c175b01668c

	column Calculation_9921103144103743
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9921103144103743
		lineageTag: 9ee96398-61c2-4671-974c-6e6047daf807

	column 'Customer Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Customer Name
		lineageTag: 11fd452e-81c1-4c08-bfaa-40a9ca93c8e3

	column Profit
		dataType: double
		summarizeBy: sum
		sourceColumn: Profit
		lineageTag: 09555f1a-b783-4cc0-bb55-52c3ed686b8c

	column Quantity
		dataType: int64
		summarizeBy: sum
		sourceColumn: Quantity
		lineageTag: 673db82b-8d73-4f57-b5d1-51b45abc4573

	column Sales
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales
		lineageTag: ffde2ffb-c436-4cb6-aca8-2553cc4bb6cb

	column 'Ship Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Ship Date
		lineageTag: 2b0686a1-7f74-42b0-9f51-6fe24e0db01f

	column 'Ship Mode'
		dataType: string
		summarizeBy: none
		sourceColumn: Ship Mode
		lineageTag: aabef14c-8545-4671-9c97-f99b59c445b4

	column Calculation_6401103171259723
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_6401103171259723
		lineageTag: b6bc6ead-cec6-4cd1-aa77-6e9a5bd004ee

	column 'Order ID'
		dataType: string
		summarizeBy: none
		sourceColumn: Order ID
		lineageTag: 7775f1ce-695f-4a90-bbb6-598954973cf4

	column 'Product Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Product Name
		lineageTag: cc9613f1-cba2-477b-a7ca-1ffe7117a32d

	column Calculation_5144658905056067585
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_5144658905056067585
		lineageTag: 8565fde4-d4fe-4b6c-bf59-c5cbff5523d7

	column Calculation_9951107165644870
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_9951107165644870
		lineageTag: 7fb90c55-8e9e-45bc-9898-828f165be2ef

	column Calculation_9060122104947471
		dataType: boolean
		summarizeBy: none
		sourceColumn: Calculation_9060122104947471
		lineageTag: 6f1d5d44-6ad4-456f-8b46-810a32ff0dfc

	column City
		dataType: string
		summarizeBy: none
		sourceColumn: City
		lineageTag: 66f00334-b0f2-4d99-8e2e-8ba2b3b4a8ba

	column Discount
		dataType: double
		summarizeBy: sum
		sourceColumn: Discount
		lineageTag: a03918eb-784c-442f-8548-588f74e3bb5a

	column 'Postal Code'
		dataType: string
		summarizeBy: none
		sourceColumn: Postal Code
		lineageTag: eb5922b6-ed05-479b-8e3e-a93c65d5784c

	column 'Sub-Category'
		dataType: string
		summarizeBy: none
		sourceColumn: Sub-Category
		lineageTag: 4cd40295-58b8-4e18-9326-1b869bd0e226

	column 'Country/Region'
		dataType: string
		summarizeBy: none
		sourceColumn: Country/Region
		lineageTag: c59d291f-dc0b-4a26-b3ed-cf9e5de1eefd

	column '__tableau_internal_object_id__].[Orders_6D2EF74F348B46BDA976A7AEEA6FB5C9'
		dataType: string
		summarizeBy: none
		sourceColumn: __tableau_internal_object_id__].[Orders_6D2EF74F348B46BDA976A7AEEA6FB5C9
		lineageTag: 34b6c71e-e16b-492a-a551-3e62c12a9fd7

	column Calculation_5421109230915137
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_5421109230915137
		lineageTag: eb1f3366-408d-433e-a554-956de4a4fb34

	column 'Sales est (copy)'
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales est (copy)
		lineageTag: 42eba933-1b45-4a01-9aeb-09a3985e334c

	column 'Sales per Customer (copy)'
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales per Customer (copy)
		lineageTag: a62f1f95-d21b-4dfd-989e-348aeb0e9d3f

	column Calculation_9330126204734562
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9330126204734562
		lineageTag: 00a6526a-3bc3-4dcc-b8e6-0090fca49c2c

	partition FullData = m
		mode: import
		source =
			let
				Source = Excel.Workbook(File.Contents("C:\Users\Pooja Satija\Downloads\tab-pbip-31-code-new-visuals\tab-pbip-31-code-new-visuals\SuperstorePBIP\Data\Superstore\\Sample - Superstore.xls"), null, true),
				OrdersTable = try Source{[Item="Orders",Kind="Table"]}[Data] otherwise null,
				OrdersSheet = try Source{[Item="Orders",Kind="Sheet"]}[Data] otherwise null,
				Selected = if OrdersTable <> null then OrdersTable else if OrdersSheet <> null then OrdersSheet else Source{0}[Data],
				Promoted = Table.PromoteHeaders(Selected, [PromoteAllScalars=true]),
				ChangedType = Table.TransformColumnTypes(Promoted, {{"Order Date", type date}, {"Ship Date", type date}, {"Sales", type number}, {"Profit", type number}, {"Discount", type number}, {"Quantity", Int64.Type}}),
				CleanNumbers = Table.TransformColumns(ChangedType, {{"Sales", each try Number.From(_) otherwise null, type number}, {"Profit", each try Number.From(_) otherwise null, type number}, {"Discount", each try Number.From(_) otherwise null, type number}, {"Quantity", each try Number.From(_) otherwise null, Int64.Type}})
			in
				CleanNumbers
	annotation PBI_ResultType = Table

