table 'Sample - Superstore'
	lineageTag: bc3dff8f-2dbe-4148-ab44-08c5e9d2f35e

	column Category
		dataType: string
		summarizeBy: none
		sourceColumn: Category
		lineageTag: 5f2fc383-34b0-4b33-bcce-56dff66bc1c2

	column 'Order Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Order Date
		lineageTag: b29012d5-7a98-4739-ae91-38002d0b0df9

	column Segment
		dataType: string
		summarizeBy: none
		sourceColumn: Segment
		lineageTag: 269e1a68-cd8e-4881-aaae-6f84e772cb04

	column Region
		dataType: string
		summarizeBy: none
		sourceColumn: Region
		lineageTag: 6ee64985-54c0-4cfa-9c3d-2d1e9584265c

	column 'State/Province'
		dataType: string
		summarizeBy: none
		sourceColumn: State/Province
		lineageTag: 0b253e3d-31f3-4eaf-a3a2-2f978a662de9

	column Calculation_0831103151444568
		dataType: int64
		summarizeBy: sum
		sourceColumn: Calculation_0831103151444568
		lineageTag: d51cb56f-6bb5-4f9b-b657-11cc96a7babd

	column Calculation_6861103170623145
		dataType: int64
		summarizeBy: sum
		sourceColumn: Calculation_6861103170623145
		lineageTag: 4eb9a451-ec0d-45a0-bc5a-3ae9ca8e422f

	column Calculation_9321103144526191
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9321103144526191
		lineageTag: 0d0a0cda-fc80-4b46-8102-1cbd8aae1339

	column Calculation_9921103144103743
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9921103144103743
		lineageTag: 55da41d0-1c95-47e3-958f-967cd3c92f04

	column 'Customer Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Customer Name
		lineageTag: b2b10e1f-4108-41cc-b496-9a3e386eb1c7

	column Profit
		dataType: double
		summarizeBy: sum
		sourceColumn: Profit
		lineageTag: 036b2a16-e713-4f51-a58b-c757f707a477

	column Quantity
		dataType: int64
		summarizeBy: sum
		sourceColumn: Quantity
		lineageTag: 0b938bc4-74ee-401d-a1eb-c5f19efc7800

	column Sales
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales
		lineageTag: 6ca6a5a3-fcaa-49a9-8398-5a52cdda7d74

	column 'Ship Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Ship Date
		lineageTag: 9bf10b9c-07fa-41da-af93-14eb069a02df

	column 'Ship Mode'
		dataType: string
		summarizeBy: none
		sourceColumn: Ship Mode
		lineageTag: bd5d79a4-ddf3-42a5-82ed-57ffb1c7a68b

	column Calculation_6401103171259723
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_6401103171259723
		lineageTag: 6cbe07a9-ef5f-4650-a599-e5661c0b0c22

	column 'Order ID'
		dataType: string
		summarizeBy: none
		sourceColumn: Order ID
		lineageTag: 1a94cdcb-7da4-4bca-9660-93901c1f2d77

	column 'Product Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Product Name
		lineageTag: d71bf725-3247-4e34-8fcb-7c390c117e35

	column Calculation_5144658905056067585
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_5144658905056067585
		lineageTag: 8f373109-2158-4d16-9b43-c916bcb21ad9

	column Calculation_9951107165644870
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_9951107165644870
		lineageTag: 7ae0b465-4a7c-4d77-a6e9-f087e0b728df

	column Calculation_9060122104947471
		dataType: boolean
		summarizeBy: none
		sourceColumn: Calculation_9060122104947471
		lineageTag: de9203f9-2f49-405a-ac5b-54dc3b6d4742

	column City
		dataType: string
		summarizeBy: none
		sourceColumn: City
		lineageTag: bbd979ff-d60e-4317-8a75-9763eca975b0

	column Discount
		dataType: double
		summarizeBy: sum
		sourceColumn: Discount
		lineageTag: 66060742-efc2-43db-8263-f15dd610d1c9

	column 'Postal Code'
		dataType: string
		summarizeBy: none
		sourceColumn: Postal Code
		lineageTag: b817a261-aefc-40f7-8e10-3ad149876b01

	column 'Sub-Category'
		dataType: string
		summarizeBy: none
		sourceColumn: Sub-Category
		lineageTag: 2156c276-1648-454e-a1d4-a164d286298f

	column 'Country/Region'
		dataType: string
		summarizeBy: none
		sourceColumn: Country/Region
		lineageTag: 2b696226-3c61-4b07-b9d7-7ac43b500335

	column '__tableau_internal_object_id__].[Orders_6D2EF74F348B46BDA976A7AEEA6FB5C9'
		dataType: string
		summarizeBy: none
		sourceColumn: __tableau_internal_object_id__].[Orders_6D2EF74F348B46BDA976A7AEEA6FB5C9
		lineageTag: ff30173d-154f-4b77-8144-75ab60901552

	column Calculation_5421109230915137
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_5421109230915137
		lineageTag: 8b0d9ee6-325a-4271-99e2-dfdd324e8e3e

	column 'Sales est (copy)'
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales est (copy)
		lineageTag: 6cd781be-8e55-479d-9a5d-380152a9196a

	column 'Sales per Customer (copy)'
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales per Customer (copy)
		lineageTag: dc5a3f82-836f-460f-b6ca-bf1ded363e8f

	column Calculation_9330126204734562
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9330126204734562
		lineageTag: 8e18a2b4-f441-4be6-a565-0458233fbc75

	partition FullData = m
		mode: import
		source =
			let
				Source = Excel.Workbook(File.Contents("C:\Users\Pooja Satija\Downloads\tab-pbip-31-code-new-visuals\tab-pbip-31-code-new-visuals\SuperstorePBIP\Data\Superstore\\Sample - Superstore.xls"), null, true),
				OrdersTable = try Source{[Item="Orders",Kind="Table"]}[Data] otherwise null,
				OrdersSheet = try Source{[Item="Orders",Kind="Sheet"]}[Data] otherwise null,
				Selected = if OrdersTable <> null then OrdersTable else if OrdersSheet <> null then OrdersSheet else Source{0}[Data],
				Promoted = Table.PromoteHeaders(Selected, [PromoteAllScalars=true]),
				ChangedType = Table.TransformColumnTypes(Promoted, {{"Order Date", type date}, {"Ship Date", type date}, {"Sales", type number}, {"Profit", type number}, {"Discount", type number}, {"Quantity", Int64.Type}}),
				CleanNumbers = Table.TransformColumns(ChangedType, {{"Sales", each try Number.From(_) otherwise null, type number}, {"Profit", each try Number.From(_) otherwise null, type number}, {"Discount", each try Number.From(_) otherwise null, type number}, {"Quantity", each try Number.From(_) otherwise null, Int64.Type}}),
				AddedMonth = Table.AddColumn(CleanNumbers, "Order Month", each Date.StartOfMonth([Order Date]), type date),
				AddedProfitability = Table.AddColumn(AddedMonth, "Profitability", each if [Profit] >= 0 then "Profitable" else "Unprofitable", type text),
				AddedYear = Table.AddColumn(AddedProfitability, "Order Year", each Date.Year([Order Date]), Int64.Type)
			in
				AddedYear
	annotation PBI_ResultType = Table

