table 'Sample - Superstore'
	lineageTag: d9abe50b-4279-489b-b102-4395f5b7dd0c

	column Category
		dataType: string
		summarizeBy: none
		sourceColumn: Category
		lineageTag: eaa4b24c-590b-452f-8f4a-cdec0907fe0e

	column 'Order Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Order Date
		lineageTag: 47bbb84b-12b1-43dc-a681-ccd0b26b613f

	column Segment
		dataType: string
		summarizeBy: none
		sourceColumn: Segment
		lineageTag: 76ae9eab-bafa-4121-b4a2-6c5be9d583e1

	column Region
		dataType: string
		summarizeBy: none
		sourceColumn: Region
		lineageTag: 3309e907-c970-43e1-8625-be16f0fded98

	column 'State/Province'
		dataType: string
		summarizeBy: none
		sourceColumn: State/Province
		lineageTag: fb5b07d8-8fb9-4a41-84aa-944ae43e4785

	column Calculation_0831103151444568
		dataType: int64
		summarizeBy: sum
		sourceColumn: Calculation_0831103151444568
		lineageTag: 57d35a57-2af9-4d41-8c12-4fb3a8907f82

	column Calculation_6861103170623145
		dataType: int64
		summarizeBy: sum
		sourceColumn: Calculation_6861103170623145
		lineageTag: 2ad9a416-9212-43fb-b031-5758d644974c

	column Calculation_9321103144526191
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9321103144526191
		lineageTag: 893aaf5f-f651-4081-8264-425b0cc3f3ad

	column Calculation_9921103144103743
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9921103144103743
		lineageTag: 25dd52ef-1ed5-49c6-bc61-558623bf1bdc

	column 'Customer Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Customer Name
		lineageTag: 046b4879-3cfa-44d5-b90b-039b3666b5db

	column Profit
		dataType: double
		summarizeBy: sum
		sourceColumn: Profit
		lineageTag: ef2d11ab-5849-42ce-891b-7ed6288b1d9b

	column Quantity
		dataType: int64
		summarizeBy: sum
		sourceColumn: Quantity
		lineageTag: 574a59d9-15e7-4383-ac49-a433f8d2e6e2

	column Sales
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales
		lineageTag: f71c0bae-7a6e-4638-8ded-6eaf207ca47f

	column 'Ship Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Ship Date
		lineageTag: 861202be-5a39-4b3f-b168-0ac8d12cf1a1

	column 'Ship Mode'
		dataType: string
		summarizeBy: none
		sourceColumn: Ship Mode
		lineageTag: 6ff921c4-2afb-424c-8551-f2ed50b795e4

	column Calculation_6401103171259723
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_6401103171259723
		lineageTag: 29a2b851-4b43-4fa2-83d9-e83ca4cb80e4

	column 'Order ID'
		dataType: string
		summarizeBy: none
		sourceColumn: Order ID
		lineageTag: edd20d46-ae51-4235-8371-ef536d6a2a4e

	column 'Product Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Product Name
		lineageTag: 8d586a37-832f-4588-8166-a051b4c49b02

	column Calculation_5144658905056067585
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_5144658905056067585
		lineageTag: fae79897-a88e-4ef1-b5c4-b0b7e51e30f4

	column Calculation_9951107165644870
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_9951107165644870
		lineageTag: c6560362-4084-42ff-9898-cc95729f61c1

	column Calculation_9060122104947471
		dataType: boolean
		summarizeBy: none
		sourceColumn: Calculation_9060122104947471
		lineageTag: 31d7986d-702e-4fe7-804b-183336c9af43

	column City
		dataType: string
		summarizeBy: none
		sourceColumn: City
		lineageTag: c100f283-f1e5-4345-a75d-0a20bf5ead1d

	column Discount
		dataType: double
		summarizeBy: sum
		sourceColumn: Discount
		lineageTag: 5884d3b1-b94e-4cd2-9d51-eefcbe908dca

	column 'Postal Code'
		dataType: string
		summarizeBy: none
		sourceColumn: Postal Code
		lineageTag: da5a16bb-6184-4e85-a9c2-b82342582889

	column 'Sub-Category'
		dataType: string
		summarizeBy: none
		sourceColumn: Sub-Category
		lineageTag: ddec35df-e298-4d3b-8c8c-379a7f1d7c6d

	column 'Country/Region'
		dataType: string
		summarizeBy: none
		sourceColumn: Country/Region
		lineageTag: b3966fdf-e2d6-4f92-b94f-88769c16a671

	column '__tableau_internal_object_id__].[Orders_6D2EF74F348B46BDA976A7AEEA6FB5C9'
		dataType: string
		summarizeBy: none
		sourceColumn: __tableau_internal_object_id__].[Orders_6D2EF74F348B46BDA976A7AEEA6FB5C9
		lineageTag: 4f54390a-70ae-41d7-a5f6-fdd853f34620

	column Calculation_5421109230915137
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_5421109230915137
		lineageTag: 2d1a4a62-363a-4b26-bd84-9a4de7378466

	column 'Sales est (copy)'
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales est (copy)
		lineageTag: 97ff583f-915c-4539-8c1c-2077c3593001

	column 'Sales per Customer (copy)'
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales per Customer (copy)
		lineageTag: 52612368-9733-48fe-8267-0b5cdccf797d

	column Calculation_9330126204734562
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9330126204734562
		lineageTag: 01e318a3-f9b0-4b52-813a-480fae425b02

	partition FullData = m
		mode: import
		source =
			let
				Source = Excel.Workbook(File.Contents("C:\Users\Pooja Satija\Downloads\tab-pbip-31-code-new-visuals\tab-pbip-31-code-new-visuals\SuperstorePBIP\Data\Superstore\\Sample - Superstore.xls"), null, true),
				OrdersTable = try Source{[Item="Orders",Kind="Table"]}[Data] otherwise null,
				OrdersSheet = try Source{[Item="Orders",Kind="Sheet"]}[Data] otherwise null,
				Selected = if OrdersTable <> null then OrdersTable else if OrdersSheet <> null then OrdersSheet else Source{0}[Data],
				Promoted = Table.PromoteHeaders(Selected, [PromoteAllScalars=true]),
				ChangedType = Table.TransformColumnTypes(Promoted, {{"Order Date", type date}, {"Ship Date", type date}, {"Sales", type number}, {"Profit", type number}, {"Discount", type number}, {"Quantity", Int64.Type}}),
				CleanNumbers = Table.TransformColumns(ChangedType, {{"Sales", each try Number.From(_) otherwise null, type number}, {"Profit", each try Number.From(_) otherwise null, type number}, {"Discount", each try Number.From(_) otherwise null, type number}, {"Quantity", each try Number.From(_) otherwise null, Int64.Type}}),
				AddedMonth = Table.AddColumn(CleanNumbers, "Order Month", each Date.StartOfMonth([Order Date]), type date),
				AddedProfitability = Table.AddColumn(AddedMonth, "Profitability", each if [Profit] >= 0 then "Profitable" else "Unprofitable", type text),
				AddedYear = Table.AddColumn(AddedProfitability, "Order Year", each Date.Year([Order Date]), Int64.Type)
			in
				AddedYear
	annotation PBI_ResultType = Table

