table 'Sample - Superstore'
	lineageTag: 676aec56-3b16-4716-a609-d8d614906334

	column Category
		dataType: string
		summarizeBy: none
		sourceColumn: Category
		lineageTag: cf9494b6-430a-4f36-b83b-60751ac3954a

	column 'Order Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Order Date
		lineageTag: b084aa57-6060-4531-9266-0ae83e4c5ff5

	column Segment
		dataType: string
		summarizeBy: none
		sourceColumn: Segment
		lineageTag: 868ae48c-e0cd-4306-a272-e4c96860b19b

	column Region
		dataType: string
		summarizeBy: none
		sourceColumn: Region
		lineageTag: 0db62bb2-547f-4cf9-bb0e-f54dede98a60

	column 'State/Province'
		dataType: string
		summarizeBy: none
		sourceColumn: State/Province
		lineageTag: 2bc21703-d3f2-4392-8250-f2cc137eaaab

	column Calculation_0831103151444568
		dataType: int64
		summarizeBy: sum
		sourceColumn: Calculation_0831103151444568
		lineageTag: 893e35c4-3bb6-4d36-9721-56e5e1893eb7

	column Calculation_6861103170623145
		dataType: int64
		summarizeBy: sum
		sourceColumn: Calculation_6861103170623145
		lineageTag: fa7743ef-bc76-40f2-a2f1-3aa2c6e2490f

	column Calculation_9321103144526191
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9321103144526191
		lineageTag: e479bdfe-55aa-4bb9-8c1a-e7dbd288d21f

	column Calculation_9921103144103743
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9921103144103743
		lineageTag: 73fe5165-09bf-46e4-b246-c48ae83592bb

	column 'Customer Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Customer Name
		lineageTag: 5f1048fb-603e-4c9c-9a17-5dcc3d688f04

	column Profit
		dataType: double
		summarizeBy: sum
		sourceColumn: Profit
		lineageTag: de292be7-fe77-43cc-a310-b29d305bc9cb

	column Quantity
		dataType: int64
		summarizeBy: sum
		sourceColumn: Quantity
		lineageTag: bae1dca9-4ac8-4347-a67f-3a4cfca9b8e0

	column Sales
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales
		lineageTag: 0f097ec8-ce7c-4e5c-812a-a5cb80ab7887

	column 'Ship Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Ship Date
		lineageTag: 4d96645a-dac7-4c2a-94da-19eec7cba6f7

	column 'Ship Mode'
		dataType: string
		summarizeBy: none
		sourceColumn: Ship Mode
		lineageTag: 8e575440-4e31-48fa-974c-be8c6a7499e0

	column Calculation_6401103171259723
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_6401103171259723
		lineageTag: 7ef1e8a2-0bd8-476f-a5cb-b509342c663e

	column 'Order ID'
		dataType: string
		summarizeBy: none
		sourceColumn: Order ID
		lineageTag: 4aa9ed45-2872-46e8-b048-0ca5cbbd58ca

	column 'Product Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Product Name
		lineageTag: 18639bd3-352c-4401-8f13-209554e388b7

	column Calculation_5144658905056067585
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_5144658905056067585
		lineageTag: d796b5a5-3e1f-4146-8da7-2e9bda861878

	column Calculation_9951107165644870
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_9951107165644870
		lineageTag: e21e6435-1fde-4b2c-ab96-0a4485d85149

	column Calculation_9060122104947471
		dataType: boolean
		summarizeBy: none
		sourceColumn: Calculation_9060122104947471
		lineageTag: ecf0745f-76fd-45ff-9e14-1b4d0b15130e

	column City
		dataType: string
		summarizeBy: none
		sourceColumn: City
		lineageTag: 873c930c-26a6-4077-a882-9c365127d518

	column Discount
		dataType: double
		summarizeBy: sum
		sourceColumn: Discount
		lineageTag: e57338d7-dedc-4775-b7e2-b44b4db53023

	column 'Postal Code'
		dataType: string
		summarizeBy: none
		sourceColumn: Postal Code
		lineageTag: 5d702f9c-4d73-4980-a753-45d5a2a8dc9f

	column 'Sub-Category'
		dataType: string
		summarizeBy: none
		sourceColumn: Sub-Category
		lineageTag: 1beeee7e-9005-4768-b2b1-5ffb24fca82e

	column 'Country/Region'
		dataType: string
		summarizeBy: none
		sourceColumn: Country/Region
		lineageTag: ee8172c4-e3cd-4426-8e26-60908d78a381

	column '__tableau_internal_object_id__].[Orders_6D2EF74F348B46BDA976A7AEEA6FB5C9'
		dataType: string
		summarizeBy: none
		sourceColumn: __tableau_internal_object_id__].[Orders_6D2EF74F348B46BDA976A7AEEA6FB5C9
		lineageTag: 9356da60-e603-4612-a2f2-d49c33c0679c

	column Calculation_5421109230915137
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_5421109230915137
		lineageTag: ec201105-69a2-49b2-9840-d6cf01a00afa

	column 'Sales est (copy)'
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales est (copy)
		lineageTag: 8249cdc7-35e7-48e0-b75d-213c7dfc97e0

	column 'Sales per Customer (copy)'
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales per Customer (copy)
		lineageTag: deb61229-fb44-4524-a941-a16384ed807c

	column Calculation_9330126204734562
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9330126204734562
		lineageTag: 681438e3-a740-40cb-88a1-1804032a63bb

	partition FullData = m
		mode: import
		source =
			let
				Source = Excel.Workbook(File.Contents("C:\Users\Pooja Satija\Downloads\tab-pbip-31-code-new-visuals\tab-pbip-31-code-new-visuals\SuperstorePBIP\Data\Superstore\\Sample - Superstore.xls"), null, true),
				OrdersTable = try Source{[Item="Orders",Kind="Table"]}[Data] otherwise null,
				OrdersSheet = try Source{[Item="Orders",Kind="Sheet"]}[Data] otherwise null,
				Selected = if OrdersTable <> null then OrdersTable else if OrdersSheet <> null then OrdersSheet else Source{0}[Data],
				Promoted = Table.PromoteHeaders(Selected, [PromoteAllScalars=true]),
				ChangedType = Table.TransformColumnTypes(Promoted, {{"Order Date", type date}, {"Ship Date", type date}, {"Sales", type number}, {"Profit", type number}, {"Discount", type number}, {"Quantity", Int64.Type}}),
				CleanNumbers = Table.TransformColumns(ChangedType, {{"Sales", each try Number.From(_) otherwise null, type number}, {"Profit", each try Number.From(_) otherwise null, type number}, {"Discount", each try Number.From(_) otherwise null, type number}, {"Quantity", each try Number.From(_) otherwise null, Int64.Type}}),
				AddedMonth = Table.AddColumn(CleanNumbers, "Order Month", each Date.StartOfMonth([Order Date]), type date),
				AddedProfitability = Table.AddColumn(AddedMonth, "Profitability", each if [Profit] >= 0 then "Profitable" else "Unprofitable", type text),
				AddedYear = Table.AddColumn(AddedProfitability, "Order Year", each Date.Year([Order Date]), Int64.Type),
				AddedDaysToShipActual = Table.AddColumn(AddedYear, "Days to Ship Actual", each Duration.Days([Ship Date] - [Order Date]), Int64.Type),
				AddedDaysToShipScheduled = Table.AddColumn(AddedDaysToShipActual, "Days to Ship Scheduled", each if [Ship Mode] = "Same Day" then 0 else if [Ship Mode] = "First Class" then 1 else if [Ship Mode] = "Second Class" then 3 else if [Ship Mode] = "Standard Class" then 6 else null, Int64.Type)
			in
				AddedDaysToShipScheduled
	annotation PBI_ResultType = Table

