table 'Sample - Superstore'
	lineageTag: bac90b97-af87-4841-bdf8-d342d7b225d1

	column Category
		dataType: string
		summarizeBy: none
		sourceColumn: Category
		lineageTag: 2258ae48-92d7-478d-89a5-2c7862714326

	column 'Order Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Order Date
		lineageTag: 04f34560-8118-4001-b759-11c0cf663ce5

	column Segment
		dataType: string
		summarizeBy: none
		sourceColumn: Segment
		lineageTag: 89e949da-0494-48f7-9b1d-5642cb8e0d7d

	column Region
		dataType: string
		summarizeBy: none
		sourceColumn: Region
		lineageTag: f225da34-ae08-4d31-922c-6f1ac7d97859

	column 'State/Province'
		dataType: string
		summarizeBy: none
		sourceColumn: State/Province
		lineageTag: 6e267f47-fc3d-4df4-9633-d7b7a0fb19a0

	column Calculation_0831103151444568
		dataType: int64
		summarizeBy: sum
		sourceColumn: Calculation_0831103151444568
		lineageTag: 54b4b9a0-3713-4530-93fb-f9ca10603e74

	column Calculation_6861103170623145
		dataType: int64
		summarizeBy: sum
		sourceColumn: Calculation_6861103170623145
		lineageTag: db2d41b7-c963-4cbe-a5fa-a0218137f945

	column Calculation_9321103144526191
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9321103144526191
		lineageTag: b112a2c9-1e80-4802-bf03-51794d8daa5a

	column Calculation_9921103144103743
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9921103144103743
		lineageTag: ab4dce44-1652-4383-a86f-481015ba4342

	column 'Customer Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Customer Name
		lineageTag: 7dbf440a-ff91-4808-9254-f7df59121c81

	column Profit
		dataType: double
		summarizeBy: sum
		sourceColumn: Profit
		lineageTag: 9b20bf29-f106-4d8b-b01b-f2274d045775

	column Quantity
		dataType: int64
		summarizeBy: sum
		sourceColumn: Quantity
		lineageTag: 55497573-5e9b-4805-a732-cb8bcce0a64d

	column Sales
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales
		lineageTag: ad9775e0-b1bc-406a-b3ee-a3e741921569

	column 'Ship Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Ship Date
		lineageTag: 56b4caae-7499-4bdb-8cac-a69fc16cf228

	column 'Ship Mode'
		dataType: string
		summarizeBy: none
		sourceColumn: Ship Mode
		lineageTag: f9d75b21-16e4-4857-9836-fc78123e6336

	column Calculation_6401103171259723
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_6401103171259723
		lineageTag: fcb1da40-ab4e-4ca2-b165-98179bb4ba60

	column 'Order ID'
		dataType: string
		summarizeBy: none
		sourceColumn: Order ID
		lineageTag: d26e3da9-17f3-4144-8f48-8c6d104f6be8

	column 'Product Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Product Name
		lineageTag: a3b892c5-0bae-49e5-b3fc-18afa91ebcbf

	column Calculation_5144658905056067585
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_5144658905056067585
		lineageTag: a6997c4f-d48c-47a7-b6dd-7e20624464c4

	column Calculation_9951107165644870
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_9951107165644870
		lineageTag: 5eb0344a-a143-4c8f-9ec5-4c0e6d00fc0e

	column Calculation_9060122104947471
		dataType: boolean
		summarizeBy: none
		sourceColumn: Calculation_9060122104947471
		lineageTag: e1ae6639-ca17-4cdb-bac2-cf82c65a8a3e

	column City
		dataType: string
		summarizeBy: none
		sourceColumn: City
		lineageTag: 316e2f1e-d7c4-4eff-a25e-43f4a9b035a4

	column Discount
		dataType: double
		summarizeBy: sum
		sourceColumn: Discount
		lineageTag: 0411013b-957f-4330-829f-0b07fab011df

	column 'Postal Code'
		dataType: string
		summarizeBy: none
		sourceColumn: Postal Code
		lineageTag: f219e475-ad58-458a-8722-f5cf65a61628

	column 'Sub-Category'
		dataType: string
		summarizeBy: none
		sourceColumn: Sub-Category
		lineageTag: 377b5ede-4b2a-448a-a1b8-eef7848491a1

	column 'Country/Region'
		dataType: string
		summarizeBy: none
		sourceColumn: Country/Region
		lineageTag: 1fb3518b-5edf-417c-af9f-2d53a057ca80

	column '__tableau_internal_object_id__].[Orders_6D2EF74F348B46BDA976A7AEEA6FB5C9'
		dataType: string
		summarizeBy: none
		sourceColumn: __tableau_internal_object_id__].[Orders_6D2EF74F348B46BDA976A7AEEA6FB5C9
		lineageTag: fcf92133-1957-48da-8116-e45685be595f

	column Calculation_5421109230915137
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_5421109230915137
		lineageTag: dcae2c06-3cef-44a0-a4a9-05b31fad89d5

	column 'Sales est (copy)'
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales est (copy)
		lineageTag: 8632b6a8-9a0c-429a-9de5-01f519ba9693

	column 'Sales per Customer (copy)'
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales per Customer (copy)
		lineageTag: cb445a14-1464-4b2e-9240-6a8532b53346

	column Calculation_9330126204734562
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9330126204734562
		lineageTag: dd4518a3-1a47-41dd-bd28-f7bf61c638f0

	partition FullData = m
		mode: import
		source =
			let
				Source = Excel.Workbook(File.Contents("C:\Users\Pooja Satija\Downloads\tab-pbip-31-code-new-visuals\tab-pbip-31-code-new-visuals\SuperstorePBIP\Data\Superstore\\Sample - Superstore.xls"), null, true),
				OrdersTable = try Source{[Item="Orders",Kind="Table"]}[Data] otherwise null,
				OrdersSheet = try Source{[Item="Orders",Kind="Sheet"]}[Data] otherwise null,
				Selected = if OrdersTable <> null then OrdersTable else if OrdersSheet <> null then OrdersSheet else Source{0}[Data],
				Promoted = Table.PromoteHeaders(Selected, [PromoteAllScalars=true]),
				ChangedType = Table.TransformColumnTypes(Promoted, {{"Order Date", type date}, {"Ship Date", type date}, {"Sales", type number}, {"Profit", type number}, {"Discount", type number}, {"Quantity", Int64.Type}}),
				CleanNumbers = Table.TransformColumns(ChangedType, {{"Sales", each try Number.From(_) otherwise null, type number}, {"Profit", each try Number.From(_) otherwise null, type number}, {"Discount", each try Number.From(_) otherwise null, type number}, {"Quantity", each try Number.From(_) otherwise null, Int64.Type}})
			in
				CleanNumbers
	annotation PBI_ResultType = Table

