table 'Sample - Superstore'
	lineageTag: d27042d8-3415-470c-a9cd-77267fcfb163

	column Category
		dataType: string
		summarizeBy: none
		sourceColumn: Category
		lineageTag: ef10cd5a-57f6-476e-870d-6227e067ae9c

	column 'Order Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Order Date
		lineageTag: 037781cf-7367-45e5-9a7e-91519eeb3aa4

	column Segment
		dataType: string
		summarizeBy: none
		sourceColumn: Segment
		lineageTag: 112e97b2-69d8-4df8-b1e4-8db225a2fcd6

	column Region
		dataType: string
		summarizeBy: none
		sourceColumn: Region
		lineageTag: 8464feb7-dc3b-4ef3-9156-9b2b83e8d44c

	column 'State/Province'
		dataType: string
		summarizeBy: none
		sourceColumn: State/Province
		lineageTag: 743351af-a324-4e6e-b523-b6df2ee34246

	column Calculation_0831103151444568
		dataType: int64
		summarizeBy: sum
		sourceColumn: Calculation_0831103151444568
		lineageTag: c00ab10f-2803-457d-822e-36b6c131c5fd

	column Calculation_6861103170623145
		dataType: int64
		summarizeBy: sum
		sourceColumn: Calculation_6861103170623145
		lineageTag: 5c9d8ad1-c041-42be-bf78-027944a8d863

	column Calculation_9321103144526191
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9321103144526191
		lineageTag: b2bca09e-961f-4627-b023-7b74be9bc6b5

	column Calculation_9921103144103743
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9921103144103743
		lineageTag: 9e0bcb8f-30fb-4873-8fbb-af67e1e844c3

	column 'Customer Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Customer Name
		lineageTag: a947d527-e95e-45a8-bee0-e6b43acc8dc3

	column Profit
		dataType: double
		summarizeBy: sum
		sourceColumn: Profit
		lineageTag: fe0e5c2d-d204-4b76-be8b-ef7abdd78191

	column Quantity
		dataType: int64
		summarizeBy: sum
		sourceColumn: Quantity
		lineageTag: 9230985b-1504-4f91-9ccf-2fae17817c4d

	column Sales
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales
		lineageTag: 45e680bc-ffd1-408a-833b-b428a6f44e9b

	column 'Ship Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Ship Date
		lineageTag: 0fffa1ed-4425-4121-8d17-4100042296c2

	column 'Ship Mode'
		dataType: string
		summarizeBy: none
		sourceColumn: Ship Mode
		lineageTag: 1324ee35-49c3-47d8-b17f-fccf36a110dd

	column Calculation_6401103171259723
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_6401103171259723
		lineageTag: aec63a79-22b8-42b3-86aa-ab716f5ac02e

	column 'Order ID'
		dataType: string
		summarizeBy: none
		sourceColumn: Order ID
		lineageTag: 14f2bccc-2d60-4eba-828a-21ae3dad13d0

	column 'Product Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Product Name
		lineageTag: 1eeb1729-fd12-447b-a90f-ad7e73ba3fce

	column Calculation_5144658905056067585
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_5144658905056067585
		lineageTag: 8b351a38-f579-4d39-9b0f-bd7c9fa3fcb4

	column Calculation_9951107165644870
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_9951107165644870
		lineageTag: a742a7f0-eec1-43e1-802e-b91051eeaa05

	column Calculation_9060122104947471
		dataType: boolean
		summarizeBy: none
		sourceColumn: Calculation_9060122104947471
		lineageTag: 4de48ac7-beab-451e-a0bc-306b9eb52c9d

	column City
		dataType: string
		summarizeBy: none
		sourceColumn: City
		lineageTag: 914ce140-3432-4dfd-a764-8142ce8afdec

	column Discount
		dataType: double
		summarizeBy: sum
		sourceColumn: Discount
		lineageTag: 8abfa724-ab41-42b4-96e6-f0988c9769a9

	column 'Postal Code'
		dataType: string
		summarizeBy: none
		sourceColumn: Postal Code
		lineageTag: 69f86140-1cfd-4872-9220-573817a0febe

	column 'Sub-Category'
		dataType: string
		summarizeBy: none
		sourceColumn: Sub-Category
		lineageTag: aeffcd28-408e-4d4f-a939-3551298975a6

	column 'Country/Region'
		dataType: string
		summarizeBy: none
		sourceColumn: Country/Region
		lineageTag: 7a3a3dac-49b4-485a-9667-0b2382ef9b44

	column '__tableau_internal_object_id__].[Orders_6D2EF74F348B46BDA976A7AEEA6FB5C9'
		dataType: string
		summarizeBy: none
		sourceColumn: __tableau_internal_object_id__].[Orders_6D2EF74F348B46BDA976A7AEEA6FB5C9
		lineageTag: 78801130-ab5a-4a1c-9370-b824d13ee710

	column Calculation_5421109230915137
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_5421109230915137
		lineageTag: e08592cf-257c-47e1-a7a7-a07dec14978a

	column 'Sales est (copy)'
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales est (copy)
		lineageTag: 9b0e11d0-60b2-4fe9-89fb-63510b0ff277

	column 'Sales per Customer (copy)'
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales per Customer (copy)
		lineageTag: 7dfbaac7-8075-471d-a035-dabd119405de

	column Calculation_9330126204734562
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9330126204734562
		lineageTag: f362af7e-edda-4714-9f42-d0f79f65232e

	partition FullData = m
		mode: import
		source =
			let
				Source = Excel.Workbook(File.Contents("C:\Users\Pooja Satija\Downloads\tab-pbip-31-code-new-visuals\tab-pbip-31-code-new-visuals\SuperstorePBIP\Data\Superstore\\Sample - Superstore.xls"), null, true),
				OrdersTable = try Source{[Item="Orders",Kind="Table"]}[Data] otherwise null,
				OrdersSheet = try Source{[Item="Orders",Kind="Sheet"]}[Data] otherwise null,
				Selected = if OrdersTable <> null then OrdersTable else if OrdersSheet <> null then OrdersSheet else Source{0}[Data],
				Promoted = Table.PromoteHeaders(Selected, [PromoteAllScalars=true]),
				ChangedType = Table.TransformColumnTypes(Promoted, {{"Order Date", type date}, {"Ship Date", type date}, {"Sales", type number}, {"Profit", type number}, {"Discount", type number}, {"Quantity", Int64.Type}}),
				CleanNumbers = Table.TransformColumns(ChangedType, {{"Sales", each try Number.From(_) otherwise null, type number}, {"Profit", each try Number.From(_) otherwise null, type number}, {"Discount", each try Number.From(_) otherwise null, type number}, {"Quantity", each try Number.From(_) otherwise null, Int64.Type}}),
				AddedMonth = Table.AddColumn(CleanNumbers, "Order Month", each Date.StartOfMonth([Order Date]), type date),
				AddedProfitability = Table.AddColumn(AddedMonth, "Profitability", each if [Profit] >= 0 then "Profitable" else "Unprofitable", type text),
				AddedYear = Table.AddColumn(AddedProfitability, "Order Year", each Date.Year([Order Date]), Int64.Type)
			in
				AddedYear
	annotation PBI_ResultType = Table

