table 'Sample - Superstore'
	lineageTag: 2bde1e66-e669-47e3-9d8a-83148f13cf0c

	column Category
		dataType: string
		summarizeBy: none
		sourceColumn: Category
		lineageTag: 0458105c-22b2-4637-a2fb-ed4f253202fd

	column 'Order Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Order Date
		lineageTag: 0477fb52-051d-4ebf-ab57-943041cb6ea3

	column Segment
		dataType: string
		summarizeBy: none
		sourceColumn: Segment
		lineageTag: 40bc10f9-80a4-4851-9b3a-c35440ad63a9

	column Region
		dataType: string
		summarizeBy: none
		sourceColumn: Region
		lineageTag: 8ffb0131-9027-4a2a-a0ba-02bd54ded625

	column 'State/Province'
		dataType: string
		summarizeBy: none
		sourceColumn: State/Province
		lineageTag: 888cd981-40d7-457a-8315-77443825d0c7

	column Calculation_0831103151444568
		dataType: int64
		summarizeBy: sum
		sourceColumn: Calculation_0831103151444568
		lineageTag: 0dfd09fd-b7f8-43b9-b717-e7f9ffe898b5

	column Calculation_6861103170623145
		dataType: int64
		summarizeBy: sum
		sourceColumn: Calculation_6861103170623145
		lineageTag: 13a7f88b-0b7b-44cd-a14b-da456e485e59

	column Calculation_9321103144526191
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9321103144526191
		lineageTag: 55ca53de-c813-4454-be38-f9c3db167a27

	column Calculation_9921103144103743
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9921103144103743
		lineageTag: d933c561-2da3-4927-9a7a-0c4194bc8f9e

	column 'Customer Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Customer Name
		lineageTag: 62225e42-656c-4d33-ad60-fd3262afa062

	column Profit
		dataType: double
		summarizeBy: sum
		sourceColumn: Profit
		lineageTag: f8e5a36b-abe7-4773-bcb7-24d64815a253

	column Quantity
		dataType: int64
		summarizeBy: sum
		sourceColumn: Quantity
		lineageTag: e330ede5-ee45-4604-89c3-f9a88dc2af09

	column Sales
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales
		lineageTag: c3497483-bb5a-4e44-877e-bb84ca120f32

	column 'Ship Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Ship Date
		lineageTag: 3b0f98f6-7cff-4d44-b8e5-acbb8318044e

	column 'Ship Mode'
		dataType: string
		summarizeBy: none
		sourceColumn: Ship Mode
		lineageTag: 88e0d120-560b-47a7-a93c-0e9fe064bf7c

	column Calculation_6401103171259723
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_6401103171259723
		lineageTag: 542bb98a-5b61-4804-ba20-d23fec513266

	column 'Order ID'
		dataType: string
		summarizeBy: none
		sourceColumn: Order ID
		lineageTag: 32e82645-85e8-4fc0-8a16-1f453f12022d

	column 'Product Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Product Name
		lineageTag: 2c1f369b-5c6b-4e40-85c6-e7ea6d5bd827

	column Calculation_5144658905056067585
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_5144658905056067585
		lineageTag: ce552fe5-be3a-4782-a2e7-351e3067ac28

	column Calculation_9951107165644870
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_9951107165644870
		lineageTag: 5da78ee5-f416-42d0-827f-70a38de0b070

	column Calculation_9060122104947471
		dataType: boolean
		summarizeBy: none
		sourceColumn: Calculation_9060122104947471
		lineageTag: f205e615-fd2b-4c3c-a1c2-4020e72b1005

	column City
		dataType: string
		summarizeBy: none
		sourceColumn: City
		lineageTag: b846b0cf-3082-4d43-b392-702e11bba85f

	column Discount
		dataType: double
		summarizeBy: sum
		sourceColumn: Discount
		lineageTag: 8f01cbd3-0306-4cb7-8e02-615c9025b1be

	column 'Postal Code'
		dataType: string
		summarizeBy: none
		sourceColumn: Postal Code
		lineageTag: 5deb1ea4-1136-40e5-bfc5-aa69660bb8b3

	column 'Sub-Category'
		dataType: string
		summarizeBy: none
		sourceColumn: Sub-Category
		lineageTag: 9238c67c-994f-41d4-be21-497fbb5d41d9

	column 'Country/Region'
		dataType: string
		summarizeBy: none
		sourceColumn: Country/Region
		lineageTag: fe6e5e61-460d-449d-99ed-49fd512d5cc9

	column '__tableau_internal_object_id__].[Orders_6D2EF74F348B46BDA976A7AEEA6FB5C9'
		dataType: string
		summarizeBy: none
		sourceColumn: __tableau_internal_object_id__].[Orders_6D2EF74F348B46BDA976A7AEEA6FB5C9
		lineageTag: 9073e1ec-7b56-4c28-9b01-e7042a424a3e

	column Calculation_5421109230915137
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_5421109230915137
		lineageTag: f2266e5c-a1f1-424c-9c4b-06154ec317af

	column 'Sales est (copy)'
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales est (copy)
		lineageTag: 2dd1e9f6-eb7f-4424-8388-024f8a7041c6

	column 'Sales per Customer (copy)'
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales per Customer (copy)
		lineageTag: c8ee3aa2-7964-4e1b-94f7-25a6175bbcdd

	column Calculation_9330126204734562
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9330126204734562
		lineageTag: 8cb00ffd-7c04-4a4e-92ff-dd68bb7410ac

	partition FullData = m
		mode: import
		source =
			let
				Source = Excel.Workbook(File.Contents("C:\Users\Pooja Satija\Downloads\tab-pbip-31-code-new-visuals\tab-pbip-31-code-new-visuals\SuperstorePBIP\Data\Superstore\\Sample - Superstore.xls"), null, true),
				OrdersTable = try Source{[Item="Orders",Kind="Table"]}[Data] otherwise null,
				OrdersSheet = try Source{[Item="Orders",Kind="Sheet"]}[Data] otherwise null,
				Selected = if OrdersTable <> null then OrdersTable else if OrdersSheet <> null then OrdersSheet else Source{0}[Data],
				Promoted = Table.PromoteHeaders(Selected, [PromoteAllScalars=true]),
				ChangedType = Table.TransformColumnTypes(Promoted, {{"Order Date", type date}, {"Ship Date", type date}, {"Sales", type number}, {"Profit", type number}, {"Discount", type number}, {"Quantity", Int64.Type}}),
				CleanNumbers = Table.TransformColumns(ChangedType, {{"Sales", each try Number.From(_) otherwise null, type number}, {"Profit", each try Number.From(_) otherwise null, type number}, {"Discount", each try Number.From(_) otherwise null, type number}, {"Quantity", each try Number.From(_) otherwise null, Int64.Type}})
			in
				CleanNumbers
	annotation PBI_ResultType = Table

