table 'Sample - Superstore'
	lineageTag: 7907d401-8c5c-4a28-938f-00d53af09232

	column Category
		dataType: string
		summarizeBy: none
		sourceColumn: Category
		lineageTag: 172133d8-48ce-40bf-bfeb-2b970ad6f7ff

	column 'Order Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Order Date
		lineageTag: 4afd56ff-539e-4886-bb07-3710061212d7

	column Segment
		dataType: string
		summarizeBy: none
		sourceColumn: Segment
		lineageTag: caa42e52-8f21-4003-b490-58a1f6c79702

	column Region
		dataType: string
		summarizeBy: none
		sourceColumn: Region
		lineageTag: 07d41227-429b-4fbf-8589-9012abcd2399

	column 'State/Province'
		dataType: string
		summarizeBy: none
		sourceColumn: State/Province
		lineageTag: dd10e2eb-cce1-4aa9-9f74-85d85c6dc3f6

	column Calculation_0831103151444568
		dataType: int64
		summarizeBy: sum
		sourceColumn: Calculation_0831103151444568
		lineageTag: bb5da4c7-a73b-4d5a-87e5-8f5e0e7ee486

	column Calculation_6861103170623145
		dataType: int64
		summarizeBy: sum
		sourceColumn: Calculation_6861103170623145
		lineageTag: bee41186-2079-444e-b527-7f07c1b113d0

	column Calculation_9321103144526191
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9321103144526191
		lineageTag: 30c2a1f5-7784-42a5-914e-c57d28986160

	column Calculation_9921103144103743
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9921103144103743
		lineageTag: 8306df3d-435f-4fca-93ff-fea245649a42

	column 'Customer Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Customer Name
		lineageTag: 695259f2-0628-4a28-8561-4e9596ecaf34

	column Profit
		dataType: double
		summarizeBy: sum
		sourceColumn: Profit
		lineageTag: dd4b71c3-4288-417e-a21c-85840d0ff8e2

	column Quantity
		dataType: int64
		summarizeBy: sum
		sourceColumn: Quantity
		lineageTag: c8bc0ca9-7766-4f03-bfec-202a752d9a67

	column Sales
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales
		lineageTag: 4649e699-4228-4002-8029-7aa99f25dd49

	column 'Ship Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Ship Date
		lineageTag: 7d2b22a3-634f-47b8-b35b-97f6a72292fb

	column 'Ship Mode'
		dataType: string
		summarizeBy: none
		sourceColumn: Ship Mode
		lineageTag: 5ff3a2ae-f8d3-4816-83f5-2569d73ef60a

	column Calculation_6401103171259723
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_6401103171259723
		lineageTag: cf88dca5-71d5-4ad6-93da-5d1f9ddcf9d6

	column 'Order ID'
		dataType: string
		summarizeBy: none
		sourceColumn: Order ID
		lineageTag: 07f8ed1f-4851-4cef-89f3-69a6cd88af6b

	column 'Product Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Product Name
		lineageTag: 3be8dd5c-d5f9-41a3-b73b-4bc66a452505

	column Calculation_5144658905056067585
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_5144658905056067585
		lineageTag: 7018077e-85f1-4d6a-95ca-2579dc989bc6

	column Calculation_9951107165644870
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_9951107165644870
		lineageTag: 8d9c8141-afec-453a-a8c6-579628cfa7f9

	column Calculation_9060122104947471
		dataType: boolean
		summarizeBy: none
		sourceColumn: Calculation_9060122104947471
		lineageTag: 918382c2-5ba5-4e52-9572-a89403f803b9

	column City
		dataType: string
		summarizeBy: none
		sourceColumn: City
		lineageTag: 6e8a09e4-b2c1-488f-a3e2-235e6e540d4c

	column Discount
		dataType: double
		summarizeBy: sum
		sourceColumn: Discount
		lineageTag: 28c826ce-70df-4f03-9b9a-5a65d43b9ba0

	column 'Postal Code'
		dataType: string
		summarizeBy: none
		sourceColumn: Postal Code
		lineageTag: 9e96823a-35d3-44c3-8e82-d1b3ebc05b28

	column 'Sub-Category'
		dataType: string
		summarizeBy: none
		sourceColumn: Sub-Category
		lineageTag: 081a44b3-5f98-45e6-b060-4750c28579fd

	column 'Country/Region'
		dataType: string
		summarizeBy: none
		sourceColumn: Country/Region
		lineageTag: c1b20b13-a563-4fcf-a9d7-9a5286392ad7

	column '__tableau_internal_object_id__].[Orders_6D2EF74F348B46BDA976A7AEEA6FB5C9'
		dataType: string
		summarizeBy: none
		sourceColumn: __tableau_internal_object_id__].[Orders_6D2EF74F348B46BDA976A7AEEA6FB5C9
		lineageTag: 55b9986f-54c4-499f-a89f-7dee35e1d079

	column Calculation_5421109230915137
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_5421109230915137
		lineageTag: 20f09d8f-27c6-4fe5-a7d7-efdd925daba1

	column 'Sales est (copy)'
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales est (copy)
		lineageTag: bf118098-c397-459e-b390-a20f80e81981

	column 'Sales per Customer (copy)'
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales per Customer (copy)
		lineageTag: a2af4c8d-cc1b-4416-9eea-6deb9ede5aeb

	column Calculation_9330126204734562
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9330126204734562
		lineageTag: 97f529ed-d006-4aa6-b691-8d400a1880c0

	partition FullData = m
		mode: import
		source =
			let
				Source = Excel.Workbook(File.Contents("C:\Users\Pooja Satija\Downloads\tab-pbip-31-code-new-visuals\tab-pbip-31-code-new-visuals\SuperstorePBIP\Data\Superstore\\Sample - Superstore.xls"), null, true),
				OrdersTable = try Source{[Item="Orders",Kind="Table"]}[Data] otherwise null,
				OrdersSheet = try Source{[Item="Orders",Kind="Sheet"]}[Data] otherwise null,
				Selected = if OrdersTable <> null then OrdersTable else if OrdersSheet <> null then OrdersSheet else Source{0}[Data],
				Promoted = Table.PromoteHeaders(Selected, [PromoteAllScalars=true]),
				ChangedType = Table.TransformColumnTypes(Promoted, {{"Order Date", type date}, {"Ship Date", type date}, {"Sales", type number}, {"Profit", type number}, {"Discount", type number}, {"Quantity", Int64.Type}}),
				CleanNumbers = Table.TransformColumns(ChangedType, {{"Sales", each try Number.From(_) otherwise null, type number}, {"Profit", each try Number.From(_) otherwise null, type number}, {"Discount", each try Number.From(_) otherwise null, type number}, {"Quantity", each try Number.From(_) otherwise null, Int64.Type}}),
				AddedMonth = Table.AddColumn(CleanNumbers, "Order Month", each Date.StartOfMonth([Order Date]), type date),
				AddedProfitability = Table.AddColumn(AddedMonth, "Profitability", each if [Profit] >= 0 then "Profitable" else "Unprofitable", type text),
				AddedYear = Table.AddColumn(AddedProfitability, "Order Year", each Date.Year([Order Date]), Int64.Type)
			in
				AddedYear
	annotation PBI_ResultType = Table

