table 'Sample - Superstore'
	lineageTag: 5de221a1-4100-4b0d-8b2d-5c5faaacdd5e

	column Category
		dataType: string
		summarizeBy: none
		sourceColumn: Category
		lineageTag: ed4e1741-8298-4580-b001-93398d615956

	column 'Order Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Order Date
		lineageTag: ba0cea42-8e1a-4972-be8b-2df1048411f7

	column Segment
		dataType: string
		summarizeBy: none
		sourceColumn: Segment
		lineageTag: bcaa3bfa-b621-40d2-b294-8150d9f33f61

	column Region
		dataType: string
		summarizeBy: none
		sourceColumn: Region
		lineageTag: 4604b989-2cbe-4437-8741-27b90057400a

	column 'State/Province'
		dataType: string
		summarizeBy: none
		sourceColumn: State/Province
		lineageTag: 137a0f15-ba98-4c82-b5e9-d426bea2ff9c

	column Calculation_0831103151444568
		dataType: int64
		summarizeBy: sum
		sourceColumn: Calculation_0831103151444568
		lineageTag: 8c8e18da-4939-4739-a735-20483b28ed32

	column Calculation_6861103170623145
		dataType: int64
		summarizeBy: sum
		sourceColumn: Calculation_6861103170623145
		lineageTag: 9baf2490-53d8-4222-96d3-4397c3cb0352

	column Calculation_9321103144526191
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9321103144526191
		lineageTag: 8d422493-b1da-409c-bade-7633096419be

	column Calculation_9921103144103743
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9921103144103743
		lineageTag: 084e9810-1b4d-4c37-8236-26b40f0803aa

	column 'Customer Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Customer Name
		lineageTag: bedba723-e0c8-48d3-88ae-b8ed0d2a07b2

	column Profit
		dataType: double
		summarizeBy: sum
		sourceColumn: Profit
		lineageTag: 9d09e631-a48b-4e16-b00f-16ac30933414

	column Quantity
		dataType: int64
		summarizeBy: sum
		sourceColumn: Quantity
		lineageTag: e5b97fd5-ef37-4146-a9e7-de928664eefe

	column Sales
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales
		lineageTag: bd901665-076a-4f44-951b-f703f194a377

	column 'Ship Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Ship Date
		lineageTag: ecd836a8-7bf1-4f7d-86ad-2e4d18c2f80b

	column 'Ship Mode'
		dataType: string
		summarizeBy: none
		sourceColumn: Ship Mode
		lineageTag: ce667e97-bdd8-4be7-adf9-681c7afb4c06

	column Calculation_6401103171259723
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_6401103171259723
		lineageTag: 1f434ffa-db7f-4c06-b846-624697bfb51d

	column 'Order ID'
		dataType: string
		summarizeBy: none
		sourceColumn: Order ID
		lineageTag: ba760fd5-495d-45a8-9c6b-9b53c09b6616

	column 'Product Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Product Name
		lineageTag: ea580af0-0594-46e1-a81f-a0260bdd479d

	column Calculation_5144658905056067585
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_5144658905056067585
		lineageTag: e9d9841c-c7a4-4889-91fd-803e51ba877d

	column Calculation_9951107165644870
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_9951107165644870
		lineageTag: b7ce2982-d3db-41ae-9d8f-bfe6f3c884e1

	column Calculation_9060122104947471
		dataType: boolean
		summarizeBy: none
		sourceColumn: Calculation_9060122104947471
		lineageTag: 51025349-6e78-49af-8f0c-32df70ad0c14

	column City
		dataType: string
		summarizeBy: none
		sourceColumn: City
		lineageTag: 565c6988-cc21-467b-bf20-6b6382239bbe

	column Discount
		dataType: double
		summarizeBy: sum
		sourceColumn: Discount
		lineageTag: 22f61be5-a86c-4278-bbfa-b55b31f70313

	column 'Postal Code'
		dataType: string
		summarizeBy: none
		sourceColumn: Postal Code
		lineageTag: 04ef2659-7e0d-4ecc-b91b-77f5e847d01b

	column 'Sub-Category'
		dataType: string
		summarizeBy: none
		sourceColumn: Sub-Category
		lineageTag: c4d172fb-87d0-43f6-9bff-98f864599821

	column 'Country/Region'
		dataType: string
		summarizeBy: none
		sourceColumn: Country/Region
		lineageTag: ef3431f9-7491-47a8-bcba-c1170f0a7441

	column '__tableau_internal_object_id__].[Orders_6D2EF74F348B46BDA976A7AEEA6FB5C9'
		dataType: string
		summarizeBy: none
		sourceColumn: __tableau_internal_object_id__].[Orders_6D2EF74F348B46BDA976A7AEEA6FB5C9
		lineageTag: a7e5bce0-c389-4d60-a603-239fa33122de

	column Calculation_5421109230915137
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_5421109230915137
		lineageTag: 0abce94c-9b9f-404e-ba3c-a8dba3073114

	column 'Sales est (copy)'
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales est (copy)
		lineageTag: 18977bf7-020c-4c98-97d3-94c07107ea59

	column 'Sales per Customer (copy)'
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales per Customer (copy)
		lineageTag: a28807e9-ca86-433e-88e9-edb0898f675e

	column Calculation_9330126204734562
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9330126204734562
		lineageTag: 8993852d-e285-4784-a10b-83e157b1aced

	partition FullData = m
		mode: import
		source =
			let
				Source = Excel.Workbook(File.Contents("C:\Users\Pooja Satija\Downloads\tab-pbip-31-code-new-visuals\tab-pbip-31-code-new-visuals\SuperstorePBIP\Data\Superstore\\Sample - Superstore.xls"), null, true),
				OrdersTable = try Source{[Item="Orders",Kind="Table"]}[Data] otherwise null,
				OrdersSheet = try Source{[Item="Orders",Kind="Sheet"]}[Data] otherwise null,
				Selected = if OrdersTable <> null then OrdersTable else if OrdersSheet <> null then OrdersSheet else Source{0}[Data],
				Promoted = Table.PromoteHeaders(Selected, [PromoteAllScalars=true]),
				ChangedType = Table.TransformColumnTypes(Promoted, {{"Order Date", type date}, {"Ship Date", type date}, {"Sales", type number}, {"Profit", type number}, {"Discount", type number}, {"Quantity", Int64.Type}}),
				CleanNumbers = Table.TransformColumns(ChangedType, {{"Sales", each try Number.From(_) otherwise null, type number}, {"Profit", each try Number.From(_) otherwise null, type number}, {"Discount", each try Number.From(_) otherwise null, type number}, {"Quantity", each try Number.From(_) otherwise null, Int64.Type}}),
				AddedMonth = Table.AddColumn(CleanNumbers, "Order Month", each Date.StartOfMonth([Order Date]), type date),
				AddedProfitability = Table.AddColumn(AddedMonth, "Profitability", each if [Profit] >= 0 then "Profitable" else "Unprofitable", type text),
				AddedYear = Table.AddColumn(AddedProfitability, "Order Year", each Date.Year([Order Date]), Int64.Type),
				AddedDaysToShipActual = Table.AddColumn(AddedYear, "Days to Ship Actual", each Duration.Days([Ship Date] - [Order Date]), Int64.Type),
				AddedDaysToShipScheduled = Table.AddColumn(AddedDaysToShipActual, "Days to Ship Scheduled", each if [Ship Mode] = "Same Day" then 0 else if [Ship Mode] = "First Class" then 1 else if [Ship Mode] = "Second Class" then 3 else if [Ship Mode] = "Standard Class" then 6 else null, Int64.Type)
			in
				AddedDaysToShipScheduled
	annotation PBI_ResultType = Table

