table 'Sample - Superstore'
	lineageTag: bcf22cb2-f284-4f97-bf23-d8e41661a879

	column Category
		dataType: string
		lineageTag: 4fa98eab-e3a9-4cbe-a370-f44de65481ab
		summarizeBy: none
		sourceColumn: Category

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 26ac342d-a05a-44ca-8c21-870c75221358
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: 9c47fa2c-dd7d-4d2f-89ad-a2e539f6652a
			defaultHierarchy: LocalDateTable_ab72eb40-3a89-4103-9377-7fbc8fc87087.'Date Hierarchy'

		annotation UnderlyingDateTimeDataType = Date

	column Segment
		dataType: string
		lineageTag: ac5f524e-dafe-4520-a056-2a066ded5b30
		summarizeBy: none
		sourceColumn: Segment

	column Region
		dataType: string
		lineageTag: 382c159d-4b3e-49e8-a27e-93e455145df1
		summarizeBy: none
		sourceColumn: Region

	column State/Province
		dataType: string
		lineageTag: fb85ef5e-5d0f-4006-85b2-a0e38f672712
		summarizeBy: none
		sourceColumn: State/Province

	column 'Customer Name'
		dataType: string
		lineageTag: 36a9bf40-0a43-4231-9f3d-23906f1ff8bd
		summarizeBy: none
		sourceColumn: Customer Name

	column Profit
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: d64c42ab-4645-45c7-9bda-51f8e82246ab
		summarizeBy: sum
		sourceColumn: Profit

	column Quantity
		dataType: int64
		lineageTag: fdeba8e5-b9ee-4edd-830e-c6412529ff93
		summarizeBy: sum
		sourceColumn: Quantity

	column Sales
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: edbbe669-febc-4226-b1c1-7c0306228fd1
		summarizeBy: sum
		sourceColumn: Sales

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d4771a04-db50-4056-9261-aa5247ce7ec9
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: 535cf86e-55e8-4eec-b190-f68799d9342e
			defaultHierarchy: LocalDateTable_3804ca52-2fec-4eab-8d77-890245705bb3.'Date Hierarchy'

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: cb472610-c72a-4ef1-bf16-152de798876e
		summarizeBy: none
		sourceColumn: Ship Mode

	column 'Order ID'
		dataType: string
		lineageTag: b2094927-48b7-473e-90a6-4e510d3d4fa4
		summarizeBy: none
		sourceColumn: Order ID

	column 'Product Name'
		dataType: string
		lineageTag: a5ca97eb-2189-471e-ade0-bb17109ce1a3
		summarizeBy: none
		sourceColumn: Product Name

	column City
		dataType: string
		lineageTag: 66f84e74-0350-4be1-8c9e-83f1fdcd5bf6
		summarizeBy: none
		sourceColumn: City

	column Discount
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: cada27db-b584-41b9-803d-00b5a3438125
		summarizeBy: sum
		sourceColumn: Discount

	column 'Postal Code'
		dataType: string
		lineageTag: 893fb4cc-12bf-44bd-854f-eaa37b969974
		summarizeBy: none
		sourceColumn: Postal Code

	column Sub-Category
		dataType: string
		lineageTag: 15739723-7626-4ad2-87e2-c5f56e0c276c
		summarizeBy: none
		sourceColumn: Sub-Category

	column Country/Region
		dataType: string
		lineageTag: f85307d3-a8e5-433f-bea4-dd6c95a97e1f
		summarizeBy: none
		sourceColumn: Country/Region

	column 'Row ID'
		dataType: string
		lineageTag: 39b3869c-fecd-4d2d-8f6e-8e2dffa121ce
		summarizeBy: none
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: af3c639a-fd17-447f-ab82-c84a1b2aa49e
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 93b1f3f0-a60c-461b-87e4-592b9c28dc73
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	partition FullData = m
		mode: import
		source =
				let
				Source = Excel.Workbook(File.Contents("C:\Users\Pooja Satija\Downloads\tab-pbip-31-code-new-visuals\tab-pbip-31-code-new-visuals\SuperstorePBIP\Data\Superstore\Sample - Superstore.xls"), null, true),
					OrdersTable = try Source{[Item="Orders",Kind="Table"]}[Data] otherwise null,
					OrdersSheet = try Source{[Item="Orders",Kind="Sheet"]}[Data] otherwise null,
					Selected = if OrdersTable <> null then OrdersTable else if OrdersSheet <> null then OrdersSheet else Source{0}[Data],
					Promoted = Table.PromoteHeaders(Selected, [PromoteAllScalars=true]),
					ChangedType = Table.TransformColumnTypes(Promoted, {{"Order Date", type date}, {"Ship Date", type date}, {"Sales", type number}, {"Profit", type number}, {"Discount", type number}, {"Quantity", Int64.Type}}),
					CleanNumbers = Table.TransformColumns(ChangedType, {{"Sales", each try Number.From(_) otherwise null, type number}, {"Profit", each try Number.From(_) otherwise null, type number}, {"Discount", each try Number.From(_) otherwise null, type number}, {"Quantity", each try Number.From(_) otherwise null, Int64.Type}})
				in
					CleanNumbers

	annotation PBI_ResultType = Table

