table 'Sample - Superstore'
	lineageTag: 66c584e1-bc76-4c66-a183-04caf4200fa9

	column Category
		dataType: string
		summarizeBy: none
		sourceColumn: Category
		lineageTag: c3f13836-dc45-4152-b851-dff550dae872

	column 'Order Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Order Date
		lineageTag: 5f288e0a-3b10-4af9-8eff-7bfcb7cee7cf

	column Segment
		dataType: string
		summarizeBy: none
		sourceColumn: Segment
		lineageTag: dc443de2-4ce3-475d-b83c-d39bef40c633

	column Region
		dataType: string
		summarizeBy: none
		sourceColumn: Region
		lineageTag: c9d8823e-0d2d-490b-a814-57080ff81d45

	column 'State/Province'
		dataType: string
		summarizeBy: none
		sourceColumn: State/Province
		lineageTag: 9a23995b-66d8-4b78-adfc-943f80b6200f

	column Calculation_0831103151444568
		dataType: int64
		summarizeBy: sum
		sourceColumn: Calculation_0831103151444568
		lineageTag: 1ddff4c7-4ae8-46dc-81aa-8140a9fdc6e7

	column Calculation_6861103170623145
		dataType: int64
		summarizeBy: sum
		sourceColumn: Calculation_6861103170623145
		lineageTag: f779698f-218b-4b90-8449-edfa5fc773a7

	column Calculation_9321103144526191
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9321103144526191
		lineageTag: ecaf6fd3-d588-4b1c-8e60-3a81143028a2

	column Calculation_9921103144103743
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9921103144103743
		lineageTag: 45a6e5dc-18d1-48fa-9424-0da00c4820df

	column 'Customer Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Customer Name
		lineageTag: 9976e0f0-ad62-4136-b0ca-63b5fb90a0d3

	column Profit
		dataType: double
		summarizeBy: sum
		sourceColumn: Profit
		lineageTag: 50703611-6d8d-4213-b024-170cb1827e98

	column Quantity
		dataType: int64
		summarizeBy: sum
		sourceColumn: Quantity
		lineageTag: c8f59f1e-d320-4302-8064-34ac63f4cdc0

	column Sales
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales
		lineageTag: 50476ffb-f134-4abc-becd-18dbe775f244

	column 'Ship Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Ship Date
		lineageTag: 9d5e3d2e-a31b-4419-ac18-7e50eae699ba

	column 'Ship Mode'
		dataType: string
		summarizeBy: none
		sourceColumn: Ship Mode
		lineageTag: 4dc147bd-3cda-4241-b615-9c67275d4939

	column Calculation_6401103171259723
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_6401103171259723
		lineageTag: 981758c9-9f27-45fd-a03e-4c81ba2216ea

	column 'Order ID'
		dataType: string
		summarizeBy: none
		sourceColumn: Order ID
		lineageTag: 3527d96a-e9e8-4cac-a6bd-0cceb4a5890e

	column 'Product Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Product Name
		lineageTag: 7d2649af-8b0c-40b9-9122-277f566a267b

	column Calculation_5144658905056067585
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_5144658905056067585
		lineageTag: 291cb49a-6e11-4060-93b8-30210cc06ef5

	column Calculation_9951107165644870
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_9951107165644870
		lineageTag: ac739baa-f31c-4e7f-aeff-2458721de648

	column Calculation_9060122104947471
		dataType: boolean
		summarizeBy: none
		sourceColumn: Calculation_9060122104947471
		lineageTag: b12554e5-88fd-43ef-a976-fc729900d4f2

	column City
		dataType: string
		summarizeBy: none
		sourceColumn: City
		lineageTag: ce5e911b-5a6f-4d82-af2b-f9f4656fa07d

	column Discount
		dataType: double
		summarizeBy: sum
		sourceColumn: Discount
		lineageTag: 8bff85a7-783d-4e67-aacc-198f0e202da3

	column 'Postal Code'
		dataType: string
		summarizeBy: none
		sourceColumn: Postal Code
		lineageTag: 6e032657-f350-4f1f-9756-eac0cfb8b022

	column 'Sub-Category'
		dataType: string
		summarizeBy: none
		sourceColumn: Sub-Category
		lineageTag: 5e60ea5f-c405-447e-90dd-e54ef62a90c3

	column 'Country/Region'
		dataType: string
		summarizeBy: none
		sourceColumn: Country/Region
		lineageTag: 357b5824-f882-4b4d-bf31-36584b76e50c

	column '__tableau_internal_object_id__].[Orders_6D2EF74F348B46BDA976A7AEEA6FB5C9'
		dataType: string
		summarizeBy: none
		sourceColumn: __tableau_internal_object_id__].[Orders_6D2EF74F348B46BDA976A7AEEA6FB5C9
		lineageTag: 7788b056-fa27-4050-8909-f6d5a762d9be

	column Calculation_5421109230915137
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_5421109230915137
		lineageTag: cb2c445b-28f6-4523-ab5e-d8229253c737

	column 'Sales est (copy)'
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales est (copy)
		lineageTag: d44c1964-6232-423a-a955-32c3670f8a09

	column 'Sales per Customer (copy)'
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales per Customer (copy)
		lineageTag: 65cd4d20-40fc-48a2-8fbf-ee0038170a14

	column Calculation_9330126204734562
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9330126204734562
		lineageTag: a46b8872-36ad-4257-bd52-66f31dea5a4d

	partition FullData = m
		mode: import
		source =
			let
				Source = Excel.Workbook(File.Contents("C:\Users\Pooja Satija\Downloads\tab-pbip-31-code-new-visuals\tab-pbip-31-code-new-visuals\SuperstorePBIP\Data\Superstore\\Sample - Superstore.xls"), null, true),
				OrdersTable = try Source{[Item="Orders",Kind="Table"]}[Data] otherwise null,
				OrdersSheet = try Source{[Item="Orders",Kind="Sheet"]}[Data] otherwise null,
				Selected = if OrdersTable <> null then OrdersTable else if OrdersSheet <> null then OrdersSheet else Source{0}[Data],
				Promoted = Table.PromoteHeaders(Selected, [PromoteAllScalars=true]),
				ChangedType = Table.TransformColumnTypes(Promoted, {{"Order Date", type date}, {"Ship Date", type date}, {"Sales", type number}, {"Profit", type number}, {"Discount", type number}, {"Quantity", Int64.Type}}),
				CleanNumbers = Table.TransformColumns(ChangedType, {{"Sales", each try Number.From(_) otherwise null, type number}, {"Profit", each try Number.From(_) otherwise null, type number}, {"Discount", each try Number.From(_) otherwise null, type number}, {"Quantity", each try Number.From(_) otherwise null, Int64.Type}}),
				AddedMonth = Table.AddColumn(CleanNumbers, "Order Month", each Date.StartOfMonth([Order Date]), type date),
				AddedProfitability = Table.AddColumn(AddedMonth, "Profitability", each if [Profit] >= 0 then "Profitable" else "Unprofitable", type text),
				AddedYear = Table.AddColumn(AddedProfitability, "Order Year", each Date.Year([Order Date]), Int64.Type)
			in
				AddedYear
	annotation PBI_ResultType = Table

