table 'Sample - Superstore'
	lineageTag: 4877b3f5-c84f-4534-9fbe-a8d140767f8e

	column Category
		dataType: string
		summarizeBy: none
		sourceColumn: Category
		lineageTag: 44ac2244-3c05-49b0-9a21-414e0193ccc0

	column 'Order Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Order Date
		lineageTag: af0ede4a-380a-4116-ace1-ff5f0a3934c4

	column Segment
		dataType: string
		summarizeBy: none
		sourceColumn: Segment
		lineageTag: 3192b702-c164-456e-9e62-e064ae0df4e5

	column Region
		dataType: string
		summarizeBy: none
		sourceColumn: Region
		lineageTag: ff6c9932-801d-4967-addd-6704970336dc

	column 'State/Province'
		dataType: string
		summarizeBy: none
		sourceColumn: State/Province
		lineageTag: d27850ac-d35d-4554-86fa-ebc425512ed5

	column Calculation_0831103151444568
		dataType: int64
		summarizeBy: sum
		sourceColumn: Calculation_0831103151444568
		lineageTag: 7afaae06-6562-4957-817c-199611d77658

	column Calculation_6861103170623145
		dataType: int64
		summarizeBy: sum
		sourceColumn: Calculation_6861103170623145
		lineageTag: d2454149-5d97-4f1f-b9de-8807dac605d1

	column Calculation_9321103144526191
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9321103144526191
		lineageTag: 47ce4583-3cc2-4851-a372-306c44323c22

	column Calculation_9921103144103743
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9921103144103743
		lineageTag: ff00fe89-f884-41c7-95d4-262124d95114

	column 'Customer Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Customer Name
		lineageTag: fe269306-7a77-4484-b2f4-3539a3d2e7a7

	column Profit
		dataType: double
		summarizeBy: sum
		sourceColumn: Profit
		lineageTag: abe43564-fa06-462c-ae40-a67fa9da59b8

	column Quantity
		dataType: int64
		summarizeBy: sum
		sourceColumn: Quantity
		lineageTag: f676600f-6172-47c8-8427-c107ff8aba31

	column Sales
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales
		lineageTag: 2a398c3c-38e6-4142-ba5e-9841d4b74225

	column 'Ship Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Ship Date
		lineageTag: d7ad62ff-9c10-431e-a4a0-f1116f1084dc

	column 'Ship Mode'
		dataType: string
		summarizeBy: none
		sourceColumn: Ship Mode
		lineageTag: 6b62b2c5-21c1-4b87-8a18-c5f6cbbdfd9e

	column Calculation_6401103171259723
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_6401103171259723
		lineageTag: cd87e87c-4594-479c-b550-1693f922f6f7

	column 'Order ID'
		dataType: string
		summarizeBy: none
		sourceColumn: Order ID
		lineageTag: 12221274-a6b8-4204-83f0-b362562febe5

	column 'Product Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Product Name
		lineageTag: 39ad0f92-c930-4039-9315-1a902d9a917c

	column Calculation_5144658905056067585
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_5144658905056067585
		lineageTag: 67d39af7-2fe6-4ead-8684-0d7cea21b553

	column Calculation_9951107165644870
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_9951107165644870
		lineageTag: 371275a9-b6af-4159-8044-cadf78bca9fe

	column Calculation_9060122104947471
		dataType: boolean
		summarizeBy: none
		sourceColumn: Calculation_9060122104947471
		lineageTag: fea41087-9b16-4879-ae77-71acf259d2e3

	column City
		dataType: string
		summarizeBy: none
		sourceColumn: City
		lineageTag: b41360ec-5a53-4a9d-b86a-6e85d4603c6b

	column Discount
		dataType: double
		summarizeBy: sum
		sourceColumn: Discount
		lineageTag: 0b2d098c-ea67-4146-b82c-0d355dce55bf

	column 'Postal Code'
		dataType: string
		summarizeBy: none
		sourceColumn: Postal Code
		lineageTag: 4fbfde2d-c37d-4d2c-8cd5-d1b017b965de

	column 'Sub-Category'
		dataType: string
		summarizeBy: none
		sourceColumn: Sub-Category
		lineageTag: 0c7959ca-a08c-4f28-aabe-be10174d0a38

	column 'Country/Region'
		dataType: string
		summarizeBy: none
		sourceColumn: Country/Region
		lineageTag: 873f1561-4686-4a7a-ba55-13e13b5840b2

	column '__tableau_internal_object_id__].[Orders_6D2EF74F348B46BDA976A7AEEA6FB5C9'
		dataType: string
		summarizeBy: none
		sourceColumn: __tableau_internal_object_id__].[Orders_6D2EF74F348B46BDA976A7AEEA6FB5C9
		lineageTag: 7efad7f3-a1aa-43c9-93dd-93c822629bbd

	column Calculation_5421109230915137
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_5421109230915137
		lineageTag: b43aee09-1a66-4564-b384-18dc050ef7b0

	column 'Sales est (copy)'
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales est (copy)
		lineageTag: 47dfa125-df22-4089-8eb0-b54b4b83b9c8

	column 'Sales per Customer (copy)'
		dataType: double
		summarizeBy: sum
		sourceColumn: Sales per Customer (copy)
		lineageTag: 4df53f4b-109d-4c83-8e2e-16754952e089

	column Calculation_9330126204734562
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_9330126204734562
		lineageTag: a8bd25a8-a2ec-4b8b-801b-17967f71169f

	partition FullData = m
		mode: import
		source =
			let
				Source = Excel.Workbook(File.Contents("C:\Users\Pooja Satija\Downloads\tab-pbip-31-code-new-visuals\tab-pbip-31-code-new-visuals\SuperstorePBIP\Data\Superstore\\Sample - Superstore.xls"), null, true),
				OrdersTable = try Source{[Item="Orders",Kind="Table"]}[Data] otherwise null,
				OrdersSheet = try Source{[Item="Orders",Kind="Sheet"]}[Data] otherwise null,
				Selected = if OrdersTable <> null then OrdersTable else if OrdersSheet <> null then OrdersSheet else Source{0}[Data],
				Promoted = Table.PromoteHeaders(Selected, [PromoteAllScalars=true]),
				ChangedType = Table.TransformColumnTypes(Promoted, {{"Order Date", type date}, {"Ship Date", type date}, {"Sales", type number}, {"Profit", type number}, {"Discount", type number}, {"Quantity", Int64.Type}}),
				CleanNumbers = Table.TransformColumns(ChangedType, {{"Sales", each try Number.From(_) otherwise null, type number}, {"Profit", each try Number.From(_) otherwise null, type number}, {"Discount", each try Number.From(_) otherwise null, type number}, {"Quantity", each try Number.From(_) otherwise null, Int64.Type}}),
				AddedMonth = Table.AddColumn(CleanNumbers, "Order Month", each Date.StartOfMonth([Order Date]), type date),
				AddedProfitability = Table.AddColumn(AddedMonth, "Profitability", each if [Profit] >= 0 then "Profitable" else "Unprofitable", type text),
				AddedYear = Table.AddColumn(AddedProfitability, "Order Year", each Date.Year([Order Date]), Int64.Type)
			in
				AddedYear
	annotation PBI_ResultType = Table

