table 'ATData+ (Accelerator Data)'
	lineageTag: 2bdaccfa-c51a-4961-98f9-3ef305ffb9f6

	column Attrition
		dataType: string
		summarizeBy: none
		sourceColumn: Attrition
		lineageTag: 0cd35847-9cc4-4277-87ee-c2d4cce03522

	column Calculation_1172624773731799054
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Calculation_1172624773731799054
		lineageTag: fda344ba-5a3b-454a-9bd5-eae12312205d

	column Calculation_1172624773744074773
		dataType: boolean
		summarizeBy: none
		sourceColumn: Calculation_1172624773744074773
		lineageTag: 3f9bcf27-7503-4c1a-bf3f-6185b939ebf0

	column Calculation_486670254084108304
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_486670254084108304
		lineageTag: decc49c6-aad7-4842-ba11-fd148db1946f

	column Calculation_602637946597855232
		dataType: boolean
		summarizeBy: none
		sourceColumn: Calculation_602637946597855232
		lineageTag: e5ed5ddf-d799-49f5-99df-d4fa178efeff

	column Calculation_740279210193760257
		dataType: boolean
		summarizeBy: none
		sourceColumn: Calculation_740279210193760257
		lineageTag: 1784ce7f-8a9d-4153-9852-6156c4868fa2

	column Calculation_866942947302453248
		dataType: int64
		summarizeBy: sum
		sourceColumn: Calculation_866942947302453248
		lineageTag: 580a2e23-4be0-4afe-be78-887092821e4e

	column Calculation_930556292295581696
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Calculation_930556292295581696
		lineageTag: bbf0203b-aad2-4364-836a-22b92ada143d

	column ChoiceID
		dataType: int64
		summarizeBy: sum
		sourceColumn: ChoiceID
		lineageTag: 840b9216-4044-49e2-bc81-50bf67294e35

	column 'Csat Score'
		dataType: int64
		summarizeBy: sum
		sourceColumn: Csat Score
		lineageTag: e75cb9ae-38dd-4fcd-a507-a9cb9d74bda7

	column Date
		dataType: string
		summarizeBy: none
		sourceColumn: Date
		lineageTag: b5478402-4e73-40b2-bfa7-4c8a71c7f9b4

	column 'Dynamic Dimension (copy)_1343480084965511168'
		dataType: string
		summarizeBy: none
		sourceColumn: Dynamic Dimension (copy)_1343480084965511168
		lineageTag: f00d7121-2315-4621-82e9-36e8b50e04a7

	column 'Dynamic KPI Suffix (copy)_1494069197481185280'
		dataType: string
		summarizeBy: none
		sourceColumn: Dynamic KPI Suffix (copy)_1494069197481185280
		lineageTag: a6ebb619-208c-48f1-b5a7-26868b46f0c4

	column 'Dynamic TT Label (copy)_1172624773745606683'
		dataType: string
		summarizeBy: none
		sourceColumn: Dynamic TT Label (copy)_1172624773745606683
		lineageTag: 2e1c31fb-a167-4716-803f-335dbc05c414

	column 'Dynamic TT Suffix (copy)_1172624773752295456'
		dataType: string
		summarizeBy: none
		sourceColumn: Dynamic TT Suffix (copy)_1172624773752295456
		lineageTag: ab3207f8-dff0-45b7-8d90-e3a9cb3a7c42

	column 'Dynamic Values (copy)_486670254112174097'
		dataType: string
		summarizeBy: none
		sourceColumn: Dynamic Values (copy)_486670254112174097
		lineageTag: 02bee248-3c94-4b41-b748-a2a3b27cbbe2

	column 'Environment Satisfaction'
		dataType: int64
		summarizeBy: sum
		sourceColumn: Environment Satisfaction
		lineageTag: 11a007b9-1277-48dd-95e8-91483d1e85f9

	column 'Filter Sheet A (copy)_1172624773740150803'
		dataType: boolean
		summarizeBy: none
		sourceColumn: Filter Sheet A (copy)_1172624773740150803
		lineageTag: 4dbe662b-ddfb-4b18-83b2-8344e0e9433f

	column Gender
		dataType: string
		summarizeBy: none
		sourceColumn: Gender
		lineageTag: 07cfd75c-eb8f-4d6d-9d24-39f033ea0685

	column 'Job Involvement'
		dataType: int64
		summarizeBy: sum
		sourceColumn: Job Involvement
		lineageTag: 218f1cf7-d80f-4205-a293-e59ec833f76c

	column 'Job Satisfaction'
		dataType: int64
		summarizeBy: sum
		sourceColumn: Job Satisfaction
		lineageTag: 55d4bf5a-c1ba-40a3-8afa-42fe7434019e

	column Pillar
		dataType: string
		summarizeBy: none
		sourceColumn: Pillar
		lineageTag: 03d20470-0fde-4ecd-b88c-d3d9f6d362d9

	column Race
		dataType: string
		summarizeBy: none
		sourceColumn: Race
		lineageTag: 254bf52b-33fc-4843-97f5-d292d5c65689

	column 'Relationship Satisfaction'
		dataType: int64
		summarizeBy: sum
		sourceColumn: Relationship Satisfaction
		lineageTag: 270de1dc-5f37-4074-9fc5-c8954f17fb2d

	column 'Response Time'
		dataType: string
		summarizeBy: none
		sourceColumn: Response Time
		lineageTag: 5efb8029-a422-45f6-bfd2-807f5f4eaf64

	column Sentiment
		dataType: string
		summarizeBy: none
		sourceColumn: Sentiment
		lineageTag: 173b8863-a129-470d-9364-aa708d4696b5

	column Severity
		dataType: string
		summarizeBy: none
		sourceColumn: Severity
		lineageTag: ebca26c2-49d0-4fe1-84fd-090233f694b6

	column 'Statisfaction Score'
		dataType: string
		summarizeBy: none
		sourceColumn: Statisfaction Score
		lineageTag: b5d3a159-1911-41a2-ac69-700e616e3675

	column 'Ticket Status'
		dataType: string
		summarizeBy: none
		sourceColumn: Ticket Status
		lineageTag: c4785774-11fd-4b9c-9bfc-0f906feb43b0

	column 'Total-Lower'
		dataType: double
		summarizeBy: sum
		sourceColumn: Total-Lower
		lineageTag: 53fcbfad-f5ca-4a7d-827e-f6ddec10b111

	column Values
		dataType: double
		summarizeBy: sum
		sourceColumn: Values
		lineageTag: 5bd95f64-24cb-4e25-b403-7239fa3d23d9

	column 'Work Life Balance'
		dataType: int64
		summarizeBy: sum
		sourceColumn: Work Life Balance
		lineageTag: 0b443b4a-c2c6-4ab9-a5b7-125c9d1413a7

	column Calculation_1172624773676371968
		dataType: boolean
		summarizeBy: none
		sourceColumn: Calculation_1172624773676371968
		lineageTag: 813f799d-46e1-4222-aab5-8b27c512cb63

	column Calculation_1172624773753921572
		dataType: boolean
		summarizeBy: none
		sourceColumn: Calculation_1172624773753921572
		lineageTag: 7476634a-bc37-4147-965b-3192d5cb93cd

	column Calculation_486670254058663936
		dataType: boolean
		summarizeBy: none
		sourceColumn: Calculation_486670254058663936
		lineageTag: c5a538e3-8660-4d22-80d2-da4b71035e01

	column 'Dynamic Columns (copy)_1172624773758930984'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Dynamic Columns (copy)_1172624773758930984
		lineageTag: 05e9f445-312a-4277-a013-81db0a8a28a1

	column 'Dynamic Columns A (copy)_1172624773762838570'
		dataType: int64
		summarizeBy: sum
		sourceColumn: Dynamic Columns A (copy)_1172624773762838570
		lineageTag: ef6102f7-74ff-4925-a508-100fa1d1ed32

	column 'Dynamic Dimension (copy)_1172624773753626657'
		dataType: boolean
		summarizeBy: none
		sourceColumn: Dynamic Dimension (copy)_1172624773753626657
		lineageTag: 8a58cd77-a4c9-40c6-af4c-2cca4f63b02f

	column 'Dynamic TT Label (copy)_1172624773733384208'
		dataType: string
		summarizeBy: none
		sourceColumn: Dynamic TT Label (copy)_1172624773733384208
		lineageTag: b400bc8d-ac16-4a9d-9867-2af9352cdac1

	column 'Dynamic TT Value (copy)_1172624773728133130'
		dataType: string
		summarizeBy: none
		sourceColumn: Dynamic TT Value (copy)_1172624773728133130
		lineageTag: abad4c81-79f3-44b4-ba62-7b1595225e1a

	column 'Dynamic Values (copy)_1172624773727506441'
		dataType: double
		summarizeBy: sum
		sourceColumn: Dynamic Values (copy)_1172624773727506441
		lineageTag: 1860d4c9-710e-45f4-867f-62ea33dbd8c5

	column 'Gender Colour (copy)_1172624773754064933'
		dataType: boolean
		summarizeBy: none
		sourceColumn: Gender Colour (copy)_1172624773754064933
		lineageTag: 670c4e40-6de1-4f65-992e-0c7dab629262

	column Metric
		dataType: string
		summarizeBy: none
		sourceColumn: Metric
		lineageTag: 9e1ed136-082e-495e-b6a0-cedd471d8e29

	column 'Race Colour (copy)_1445374026211987456'
		dataType: boolean
		summarizeBy: none
		sourceColumn: Race Colour (copy)_1445374026211987456
		lineageTag: a7d0ad14-6ee7-4ea6-a98a-17505c0d5483

	column 'Response Colour (copy)_1445374026222034946'
		dataType: boolean
		summarizeBy: none
		sourceColumn: Response Colour (copy)_1445374026222034946
		lineageTag: 111f9425-ee07-486e-9c21-a4868e04e743

	column 'Satisfaction Colour (copy)_1343480084970881027'
		dataType: boolean
		summarizeBy: none
		sourceColumn: Satisfaction Colour (copy)_1343480084970881027
		lineageTag: 1b7c9a35-eef1-45ff-aa44-b09317c451dd

	column 'Sentiment Colour (copy)_1343480084969295874'
		dataType: boolean
		summarizeBy: none
		sourceColumn: Sentiment Colour (copy)_1343480084969295874
		lineageTag: c16814d2-39c5-4d26-a62a-e6d2ccc4de8f

	column 'Sentiment Colour (copy)_887490622636527617'
		dataType: boolean
		summarizeBy: none
		sourceColumn: Sentiment Colour (copy)_887490622636527617
		lineageTag: 6d15c7fe-5229-4208-b364-2bd65e67a4d1

	column '16P Profile'
		dataType: string
		summarizeBy: none
		sourceColumn: 16P Profile
		lineageTag: 637e5dc7-0a9c-4116-ac9a-9d491102844e

	column 'Age (bin)'
		dataType: int64
		summarizeBy: sum
		sourceColumn: Age (bin)
		lineageTag: 8b10efad-5ff1-432e-9c17-5389601c5ae3

	column Calculation_1172624773730148364
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_1172624773730148364
		lineageTag: b6be9369-16e3-460c-8b9a-dc03e462d374

	column Calculation_602637946600284163
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_602637946600284163
		lineageTag: e46e633c-433c-44d6-a13b-64e3b2656550

	column 'Days Open Bin (copy)_602637946603446276'
		dataType: string
		summarizeBy: none
		sourceColumn: Days Open Bin (copy)_602637946603446276
		lineageTag: 3ea387e8-9370-4431-9ef2-c865b0f78e0f

	column 'Dynamic Columns B (copy)_740279210191249408'
		dataType: string
		summarizeBy: none
		sourceColumn: Dynamic Columns B (copy)_740279210191249408
		lineageTag: 8eddbc73-9739-4467-8d58-0190dbcf7ada

	column 'Dynamic TT Label (copy)_1172624773729112075'
		dataType: string
		summarizeBy: none
		sourceColumn: Dynamic TT Label (copy)_1172624773729112075
		lineageTag: 76af444f-ede3-400c-89d8-f348389ee38a

	column 'Dynamic Values (copy)_1172624773690847239'
		dataType: string
		summarizeBy: none
		sourceColumn: Dynamic Values (copy)_1172624773690847239
		lineageTag: 8ced5aba-4ce2-42fd-8c6a-38bb7a28623e

	column 'Dynamic Values (copy)_486670254113632275'
		dataType: string
		summarizeBy: none
		sourceColumn: Dynamic Values (copy)_486670254113632275
		lineageTag: ae35a295-751e-4c8a-a0d2-632f69bc20f7

	column 'Energy Desc'
		dataType: string
		summarizeBy: none
		sourceColumn: Energy Desc
		lineageTag: d2c99517-c4b0-4be4-9b10-07f10b17716e

	column 'Energy Tag'
		dataType: string
		summarizeBy: none
		sourceColumn: Energy Tag
		lineageTag: 63840695-5eb2-4af9-82bc-327264d1fe84

	column 'Identity Desc'
		dataType: string
		summarizeBy: none
		sourceColumn: Identity Desc
		lineageTag: ed8eedda-1c42-4330-b0ba-119c61bf4118

	column 'Identity Tag'
		dataType: string
		summarizeBy: none
		sourceColumn: Identity Tag
		lineageTag: 6a3ed076-5458-4887-8983-e1d0edb112f7

	column 'Mind Desc'
		dataType: string
		summarizeBy: none
		sourceColumn: Mind Desc
		lineageTag: 5b267a24-4717-4e27-913a-1d94b451e2ab

	column 'Mind Tag'
		dataType: string
		summarizeBy: none
		sourceColumn: Mind Tag
		lineageTag: b6d30bc4-a5f9-4031-8648-52c3a12fa8a9

	column 'Nature Desc'
		dataType: string
		summarizeBy: none
		sourceColumn: Nature Desc
		lineageTag: 7f622ca2-a606-49c2-8385-f38d5e91c375

	column 'Nature Tag'
		dataType: string
		summarizeBy: none
		sourceColumn: Nature Tag
		lineageTag: a41f5a2b-7b42-4f90-9782-69c354217d9b

	column 'Profile Code'
		dataType: string
		summarizeBy: none
		sourceColumn: Profile Code
		lineageTag: 4c3f0103-0b1c-4305-965b-e3ca1a5dc424

	column 'Profile Desc'
		dataType: string
		summarizeBy: none
		sourceColumn: Profile Desc
		lineageTag: 7dafc53f-39ff-4b96-93e3-a2f39e73d6dc

	column 'Show Sheet A (copy)_1172624773676642305'
		dataType: boolean
		summarizeBy: none
		sourceColumn: Show Sheet A (copy)_1172624773676642305
		lineageTag: 5a3a57cd-5085-4fe8-921e-2f71243c2e84

	column 'Tactics Desc'
		dataType: string
		summarizeBy: none
		sourceColumn: Tactics Desc
		lineageTag: af1799ba-1a7a-4075-9d48-0f628b4d4cb0

	column 'Tactics Tag'
		dataType: string
		summarizeBy: none
		sourceColumn: Tactics Tag
		lineageTag: 2bc17f5f-a070-49ae-934c-d2e7889b4690

	column 'Tenure (bin)'
		dataType: int64
		summarizeBy: sum
		sourceColumn: Tenure (bin)
		lineageTag: 23c773f9-4af9-4bf0-9a3b-12df2a955ef0

	column 'P1M1Boolean (copy)_602637946607476746'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P1M1Boolean (copy)_602637946607476746
		lineageTag: 4c676669-060a-41aa-a608-c77bbaa68f31

	column 'P1M2Boolean (copy)_602637946607566859'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P1M2Boolean (copy)_602637946607566859
		lineageTag: a516e758-c993-481e-9f91-1185cb62b388

	column 'P1Chart Check (copy 2)_602637946607054854'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P1Chart Check (copy 2)_602637946607054854
		lineageTag: 1c8c296b-f7e8-455d-b7cc-6ba7f7ea9c32

	column 'P1M2Boolean (copy)_602637946607861773'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P1M2Boolean (copy)_602637946607861773
		lineageTag: 0fa92cff-418f-4480-9b03-d36258091987

	column 'P1M3Boolean (copy)_602637946607861774'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P1M3Boolean (copy)_602637946607861774
		lineageTag: 05ee789b-80fd-45d6-b2b7-66ecf8d36542

	column 'P1Chart Check (copy)_602637946607030277'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P1Chart Check (copy)_602637946607030277
		lineageTag: d84da87a-bff0-4e2a-a031-81387f01dfd3

	column 'P1M1Boolean (copy)_602637946608648213'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P1M1Boolean (copy)_602637946608648213
		lineageTag: 3853146a-323d-415a-b6b3-2ab5e5d62ef4

	column 'P1M2Boolean (copy)_602637946608648214'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P1M2Boolean (copy)_602637946608648214
		lineageTag: 796d828b-78a9-4f5a-90a5-445160327ac1

	column 'P1M3Boolean (copy)_602637946608648216'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P1M3Boolean (copy)_602637946608648216
		lineageTag: 98ed2801-2416-4863-a700-c7b9e161af05

	column 'P1Chart Check (copy) (copy 2)_602637946607075337'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P1Chart Check (copy) (copy 2)_602637946607075337
		lineageTag: bc9df1ef-0a5e-4588-a0e6-8117a4b1ba05

	column 'P1M1Boolean (copy)_602637946608107535'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P1M1Boolean (copy)_602637946608107535
		lineageTag: 80c24869-e9e7-4acd-a6a1-298785da1c64

	column 'P1M2Boolean (copy)_602637946608107536'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P1M2Boolean (copy)_602637946608107536
		lineageTag: 98e3a2b2-1429-4941-84d1-c9b6c8c8caa5

	column 'P1M3Boolean (copy)_602637946608107538'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P1M3Boolean (copy)_602637946608107538
		lineageTag: cf3f5ea4-af33-42e8-beca-fe0a7474a139

	column 'P1Chart Check (copy) (copy)_602637946607054855'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P1Chart Check (copy) (copy)_602637946607054855
		lineageTag: 80faad11-97fd-4145-b6d9-a9546de2f2b8

	column 'P2M1Boolean (copy)_602637946608107537'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P2M1Boolean (copy)_602637946608107537
		lineageTag: c77cf126-5618-454e-8f31-f9ce8d9e1c3b

	column 'P2M2Boolean (copy)_602637946608107539'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P2M2Boolean (copy)_602637946608107539
		lineageTag: aa77c813-01fa-4212-90f2-8e9cfe83da6a

	column 'P3M3Boolean (copy)_602637946608107540'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P3M3Boolean (copy)_602637946608107540
		lineageTag: aa255ecd-58c5-4cc8-8afb-d170382807d6

	column 'P1Chart Check (copy) (copy) (copy)_602637946607075336'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P1Chart Check (copy) (copy) (copy)_602637946607075336
		lineageTag: 428b5aa4-2e0d-4914-ae0c-736cc82dcf09

	column 'P2M1Boolean (copy)_602637946608648215'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P2M1Boolean (copy)_602637946608648215
		lineageTag: 895cc2fa-1a72-4c7c-a9a4-2605b45a5b23

	column 'P2M2Boolean (copy)_602637946608648217'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P2M2Boolean (copy)_602637946608648217
		lineageTag: 8d74f981-a312-41bd-9bfb-226df619207f

	column 'P2M3Boolean (copy)_602637946608648218'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P2M3Boolean (copy)_602637946608648218
		lineageTag: 05cf4ec6-2549-400a-a236-080f55c7c9fa

	partition FullData = m
		mode: import
		source =
			let
				Direct1 = "C:\Users\Pooja Satija\Downloads\tab-pbip-31-code-new-visuals\tab-pbip-31-code-new-visuals\ExecutiveKPITest\Data\HyperExports\ATData+ (Accelerator Data).csv",
				Direct2 = "C:\Users\dhrsharm\Downloads\tab-pbip-31\ExecutiveKPITest\Data\HyperExports\ATData+ (Accelerator Data).csv",
				Direct3 = "C:\Users\dhrsharm\Downloads\ExecutiveKPITest\Data\HyperExports\ATData+ (Accelerator Data).csv",
				Source = try Csv.Document(File.Contents(Direct1), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None])
					otherwise try Csv.Document(File.Contents(Direct2), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None])
					otherwise try Csv.Document(File.Contents(Direct3), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None])
					otherwise
						let
							Found = try Table.First(Table.SelectRows(Folder.Files("C:\Users\Pooja Satija\Downloads"), each [Name] = "ATData+ (Accelerator Data).csv")) otherwise null,
							Path = if Found = null then error "ATData CSV not found under Downloads" else Found[Folder Path] & Found[Name]
						in
							Csv.Document(File.Contents(Path), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				Promoted
	annotation PBI_ResultType = Table

