table 'Metric Lookup (Metric List)'
	lineageTag: 26ab5832-db5b-4ae1-ac4e-5e4a643285d1

	column Calculation_571675699479650349
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_571675699479650349
		lineageTag: 33e2b3ba-87aa-40b6-8cbe-d99ca00f9b07

	column Calculation_571675699480363056
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_571675699480363056
		lineageTag: 696f95f8-f167-46df-b121-0ced02fa0684

	column 'Reset (copy)_571675699484540977'
		dataType: int64
		summarizeBy: sum
		sourceColumn: Reset (copy)_571675699484540977
		lineageTag: f2eddc36-2ffe-4835-93fd-2a3bc377aa4c

	column Calculation_1429611422894678023
		dataType: boolean
		summarizeBy: none
		sourceColumn: Calculation_1429611422894678023
		lineageTag: 1af80297-fabf-43dd-9ec4-049399f1cc77

	column Calculation_1558526964368723970
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_1558526964368723970
		lineageTag: f6ff2f89-4d7a-434c-93e3-36f501f22f0f

	column Calculation_571675699473780736
		dataType: boolean
		summarizeBy: none
		sourceColumn: Calculation_571675699473780736
		lineageTag: 74ab8c3a-f13b-4af6-a506-35e91bce7617

	column Calculation_571675699474571268
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_571675699474571268
		lineageTag: 26480716-d478-490a-bdfd-f214ece8799e

	column Metric
		dataType: string
		summarizeBy: none
		sourceColumn: Metric
		lineageTag: 295e439b-1e14-41a6-9d85-30d947eb7554

	column Metric_ID
		dataType: int64
		summarizeBy: sum
		sourceColumn: Metric_ID
		lineageTag: 77324090-374d-41dd-9145-d43b741174f1

	column Pillar
		dataType: int64
		summarizeBy: sum
		sourceColumn: Pillar
		lineageTag: 19697210-d30c-4a13-86b0-5a6e1818943f

	column Calculation_1558526964362117120
		dataType: string
		summarizeBy: none
		sourceColumn: Calculation_1558526964362117120
		lineageTag: 36797c59-ecc6-46d3-ad92-1699d7e440a9

	column Calculation_571675699476213771
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_571675699476213771
		lineageTag: 3524d347-4ccf-486d-8a3a-de1e717d674b

	column 'M1Title (copy)_78531536883646465'
		dataType: string
		summarizeBy: none
		sourceColumn: M1Title (copy)_78531536883646465
		lineageTag: ceed4890-db55-4fdd-92b0-fa4b27ec4423

	column Calculation_571675699476455437
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_571675699476455437
		lineageTag: a004b5d8-a869-4af0-8587-b00308d97087

	column 'P1M2Title (copy)_78531536884060162'
		dataType: string
		summarizeBy: none
		sourceColumn: P1M2Title (copy)_78531536884060162
		lineageTag: d62c454e-a265-4a6c-85c8-e3f56966727d

	column Calculation_571675699476590607
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_571675699476590607
		lineageTag: 7fdcde1d-d89e-49f6-9d31-726178483dc7

	column 'P1 Colour (copy)_571675699475509253'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P1 Colour (copy)_571675699475509253
		lineageTag: 2e1ce601-fae6-48f5-9fae-ce3899d47ec8

	column 'P1 Filter (copy)_1429611422895149064'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P1 Filter (copy)_1429611422895149064
		lineageTag: a2908c18-2f7e-41b2-bf65-fc5fb9f90e5e

	column 'P1M1Title (copy 2)_78531536884838417'
		dataType: string
		summarizeBy: none
		sourceColumn: P1M1Title (copy 2)_78531536884838417
		lineageTag: 056e2030-e3ab-4ef6-90cb-0f2d65d0d5c4

	column Calculation_571675699476770833
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_571675699476770833
		lineageTag: e97f6358-c085-4d79-8ef6-d68440df48b4

	column 'P1M2Title (copy 2)_78531536884817936'
		dataType: string
		summarizeBy: none
		sourceColumn: P1M2Title (copy 2)_78531536884817936
		lineageTag: 4d564cf9-3d84-4aac-abb6-e808930e1237

	column Calculation_571675699476901907
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_571675699476901907
		lineageTag: 3999072e-a475-4229-ad46-67ec7363fb02

	column 'P1M3Title (copy)_78531536884273155'
		dataType: string
		summarizeBy: none
		sourceColumn: P1M3Title (copy)_78531536884273155
		lineageTag: f0cb7599-7f4f-4e82-9987-68945841d9b9

	column Calculation_571675699477213205
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_571675699477213205
		lineageTag: d7d6053a-934c-4119-b1a7-e1573cd765f7

	column 'P1 Colour (copy) (copy)_571675699475525638'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P1 Colour (copy) (copy)_571675699475525638
		lineageTag: af30be8c-172d-4561-9d76-69c2c7764cd9

	column 'P1 Filter (copy)_1429611422896226313'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P1 Filter (copy)_1429611422896226313
		lineageTag: 4a879bec-83d9-419d-bdf8-07809405f56a

	column 'P1M1Title (copy)_78531536884727812'
		dataType: string
		summarizeBy: none
		sourceColumn: P1M1Title (copy)_78531536884727812
		lineageTag: 047fa0d5-fcef-4aa2-96b1-7b3f22020ec2

	column Calculation_571675699477405719
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_571675699477405719
		lineageTag: 27a8b5cf-b059-40f6-86a0-d70ccc62d31e

	column 'P1M2Title (copy)_78531536884727813'
		dataType: string
		summarizeBy: none
		sourceColumn: P1M2Title (copy)_78531536884727813
		lineageTag: 246b5872-3635-4d15-ba61-3b32d7f52fbe

	column Calculation_571675699477532697
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_571675699477532697
		lineageTag: 8f806326-4058-4e70-ad8a-af54ad75ec28

	column 'P1M3Title (copy)_78531536884727814'
		dataType: string
		summarizeBy: none
		sourceColumn: P1M3Title (copy)_78531536884727814
		lineageTag: 8b8dab7b-d3e5-450d-87a0-e0f3e2b07bf0

	column Calculation_571675699477651483
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_571675699477651483
		lineageTag: 2f003bd3-bba0-4c43-959a-4fc3003a47cf

	column 'P1 Colour (copy) (copy) (copy)_571675699475542023'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P1 Colour (copy) (copy) (copy)_571675699475542023
		lineageTag: 2357f92c-02d0-45bf-841b-6208e8b236df

	column 'P1 Filter (copy) (copy)_1429611422896234507'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P1 Filter (copy) (copy)_1429611422896234507
		lineageTag: 12ff6398-1984-4da9-8c61-879da5e4e840

	column 'P1M1Title (copy) (copy)_78531536884744199'
		dataType: string
		summarizeBy: none
		sourceColumn: P1M1Title (copy) (copy)_78531536884744199
		lineageTag: 85e59e17-eb4f-4630-9295-57c3538357ea

	column Calculation_571675699477811229
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_571675699477811229
		lineageTag: f3a46636-b277-46ff-bcf2-b1ae13a4c225

	column 'P1M2Title (copy) (copy)_78531536884744200'
		dataType: string
		summarizeBy: none
		sourceColumn: P1M2Title (copy) (copy)_78531536884744200
		lineageTag: 6090c84e-3767-4803-8da5-2ccbe9aab430

	column Calculation_571675699477917727
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_571675699477917727
		lineageTag: e05d3654-d75f-4d9d-a60e-764c9399348a

	column 'P1M3Title (copy) (copy)_78531536884744201'
		dataType: string
		summarizeBy: none
		sourceColumn: P1M3Title (copy) (copy)_78531536884744201
		lineageTag: da3e0c32-d10b-4901-9c9d-f3043ef07bd6

	column Calculation_571675699478487073
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_571675699478487073
		lineageTag: c5960ed3-1f78-47ba-aa52-b3abe7940279

	column 'P1 Colour (copy) (copy) (copy) (copy)_571675699475550216'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P1 Colour (copy) (copy) (copy) (copy)_571675699475550216
		lineageTag: 5cbc9c4d-9207-4f39-87c8-3fecc1192ada

	column 'P2 Filter (copy)_1429611422896226314'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P2 Filter (copy)_1429611422896226314
		lineageTag: cf25c49f-cedb-460d-991d-c844a69ad365

	column 'P1M1Title (copy) (copy) (copy)_78531536884756490'
		dataType: string
		summarizeBy: none
		sourceColumn: P1M1Title (copy) (copy) (copy)_78531536884756490
		lineageTag: f7cb63c3-2c76-4b33-a62e-a03cd99f229d

	column Calculation_571675699478655011
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_571675699478655011
		lineageTag: 9ee679ef-51d4-4213-966a-822634fdeb2b

	column 'P1M2Title (copy) (copy) (copy)_78531536884756491'
		dataType: string
		summarizeBy: none
		sourceColumn: P1M2Title (copy) (copy) (copy)_78531536884756491
		lineageTag: cef26ec5-01cd-418d-b775-9d7988eabfae

	column Calculation_571675699478757413
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_571675699478757413
		lineageTag: d62be7bd-88bc-4a67-b3ee-5f74d2efcb33

	column 'P1M3Title (copy) (copy) (copy)_78531536884756492'
		dataType: string
		summarizeBy: none
		sourceColumn: P1M3Title (copy) (copy) (copy)_78531536884756492
		lineageTag: 3b8ab590-411c-46ca-b640-0c78ac39aad6

	column Calculation_571675699478872103
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_571675699478872103
		lineageTag: 866f21fa-a47b-4b0b-91ac-47348ea70152

	column 'P1 Colour (copy) (copy) (copy) (copy) (copy)_571675699475558409'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P1 Colour (copy) (copy) (copy) (copy) (copy)_571675699475558409
		lineageTag: 4cfae6ec-4291-493f-bace-078e6fc577a1

	column 'P2 Filter (copy) (copy)_1429611422896234508'
		dataType: boolean
		summarizeBy: none
		sourceColumn: P2 Filter (copy) (copy)_1429611422896234508
		lineageTag: 5a0e1106-eae1-46dc-a988-33671b3f4ae3

	column 'P1M1Title (copy) (copy) (copy) (copy)_78531536884772877'
		dataType: string
		summarizeBy: none
		sourceColumn: P1M1Title (copy) (copy) (copy) (copy)_78531536884772877
		lineageTag: 3ac7d8c5-6732-4021-a0b0-3644eda09a13

	column Calculation_571675699479031849
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_571675699479031849
		lineageTag: ecdfe20f-47b3-411b-a560-61ea1547fd2f

	column 'P1M2Title (copy) (copy) (copy) (copy)_78531536884772878'
		dataType: string
		summarizeBy: none
		sourceColumn: P1M2Title (copy) (copy) (copy) (copy)_78531536884772878
		lineageTag: 91bec9b5-91f9-4dfc-94bc-c32004188ae6

	column Calculation_571675699479130155
		dataType: double
		summarizeBy: sum
		sourceColumn: Calculation_571675699479130155
		lineageTag: b709ffdd-6015-43a4-8ab6-adfb48f258a5

	column 'P1M3Title (copy) (copy) (copy) (copy)_78531536884772879'
		dataType: string
		summarizeBy: none
		sourceColumn: P1M3Title (copy) (copy) (copy) (copy)_78531536884772879
		lineageTag: 0628b5da-5435-4a0e-963f-e571e40b5619

	partition FullData = m
		mode: import
		source =
			let
				Direct1 = "C:\Users\Pooja Satija\Downloads\tab-pbip-31-code-new-visuals\tab-pbip-31-code-new-visuals\ExecutiveKPITest\Data\HyperExports\Metric Lookup (Metric List).csv",
				Direct2 = "C:\Users\dhrsharm\Downloads\tab-pbip-31\ExecutiveKPITest\Data\HyperExports\Metric Lookup (Metric List).csv",
				Direct3 = "C:\Users\dhrsharm\Downloads\ExecutiveKPITest\Data\HyperExports\Metric Lookup (Metric List).csv",
				Source = try Csv.Document(File.Contents(Direct1), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None])
					otherwise try Csv.Document(File.Contents(Direct2), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None])
					otherwise try Csv.Document(File.Contents(Direct3), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None])
					otherwise
						let
							Found = try Table.First(Table.SelectRows(Folder.Files("C:\Users\Pooja Satija\Downloads"), each [Name] = "Metric Lookup (Metric List).csv")) otherwise null,
							Path = if Found = null then error "Metric Lookup CSV not found under Downloads" else Found[Folder Path] & Found[Name]
						in
							Csv.Document(File.Contents(Path), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				Promoted
	annotation PBI_ResultType = Table

