table Parameters
	lineageTag: 3c6a5b3e-a772-49ca-9a81-50be9d5dc299

	column 'Months Back (copy)_468655857391050752'
		dataType: int64
		summarizeBy: sum
		sourceColumn: Months Back (copy)_468655857391050752
		lineageTag: 343f0b1e-68a8-4626-b7c9-7931b9164703

	column 'Parameter 1'
		dataType: double
		summarizeBy: sum
		sourceColumn: Parameter 1
		lineageTag: 197a7855-f9fe-44d8-aeb2-e7ecf6997603

	column 'Parameter 3'
		dataType: string
		summarizeBy: none
		sourceColumn: Parameter 3
		lineageTag: 26668881-c4c7-4141-a598-6d409a715ad7

	column 'Parameter 4'
		dataType: string
		summarizeBy: none
		sourceColumn: Parameter 4
		lineageTag: 0dd5fe7e-75c6-4c9a-b168-c43da92c2358

	column 'Parameter 7'
		dataType: int64
		summarizeBy: sum
		sourceColumn: Parameter 7
		lineageTag: a44018fc-2d87-448d-bff7-7bc7b685868f

	column 'Parameter 8'
		dataType: string
		summarizeBy: none
		sourceColumn: Parameter 8
		lineageTag: 21b0da55-adda-419f-8117-4ecb79644038

	column 'p.P1M1Selection (copy)_1429611422903926798'
		dataType: string
		summarizeBy: none
		sourceColumn: p.P1M1Selection (copy)_1429611422903926798
		lineageTag: 93a6c102-3faa-4598-ac3d-91637ab9c65f

	column 'p.P1M1Selection (copy)_1429611422904180756'
		dataType: string
		summarizeBy: none
		sourceColumn: p.P1M1Selection (copy)_1429611422904180756
		lineageTag: 86495625-c4d9-4397-9126-8782f5a29c1c

	column 'p.P1M2Selection (copy)_1429611422903877645'
		dataType: string
		summarizeBy: none
		sourceColumn: p.P1M2Selection (copy)_1429611422903877645
		lineageTag: f15babf6-c071-4356-8cff-09724ee45540

	column 'p.P1M2Selection (copy)_1429611422903926799'
		dataType: string
		summarizeBy: none
		sourceColumn: p.P1M2Selection (copy)_1429611422903926799
		lineageTag: a9dd5e17-48ef-4ee3-9ecf-c9608a30f9a4

	column 'p.P1M2Selection (copy)_1429611422904180757'
		dataType: string
		summarizeBy: none
		sourceColumn: p.P1M2Selection (copy)_1429611422904180757
		lineageTag: 17ba4b9a-ef69-45ec-973c-4dcb51a398ac

	column 'p.P1M3Selection (copy)_1429611422903926800'
		dataType: string
		summarizeBy: none
		sourceColumn: p.P1M3Selection (copy)_1429611422903926800
		lineageTag: 841fa3e9-4c19-45b5-af5a-2bb0dda6df69

	column 'p.P1M3Selection (copy)_1429611422904180759'
		dataType: string
		summarizeBy: none
		sourceColumn: p.P1M3Selection (copy)_1429611422904180759
		lineageTag: 2d3aa68e-2804-4e4c-9346-c04d7e0b6e4c

	column 'p.P2M1Selection (copy)_1429611422904061969'
		dataType: string
		summarizeBy: none
		sourceColumn: p.P2M1Selection (copy)_1429611422904061969
		lineageTag: 9aac6c1a-a4d6-4f40-ba64-b68f8e347429

	column 'p.P2M1Selection (copy)_1429611422904180758'
		dataType: string
		summarizeBy: none
		sourceColumn: p.P2M1Selection (copy)_1429611422904180758
		lineageTag: 5073c60d-ab42-4353-a8dd-473df2310d68

	column 'p.P2M2Selection (copy)_1429611422904061970'
		dataType: string
		summarizeBy: none
		sourceColumn: p.P2M2Selection (copy)_1429611422904061970
		lineageTag: dc707525-5ed6-4a63-a24e-03d6935f836a

	column 'p.P2M2Selection (copy)_1429611422904180760'
		dataType: string
		summarizeBy: none
		sourceColumn: p.P2M2Selection (copy)_1429611422904180760
		lineageTag: 0a8cd8d3-f673-4917-8d84-2da0d9aec119

	column 'p.P2M3Selection (copy)_1429611422904061971'
		dataType: string
		summarizeBy: none
		sourceColumn: p.P2M3Selection (copy)_1429611422904061971
		lineageTag: a4217302-6b0a-473e-aca1-cc3aabef3d17

	column 'p.P2M3Selection (copy)_1429611422904180761'
		dataType: string
		summarizeBy: none
		sourceColumn: p.P2M3Selection (copy)_1429611422904180761
		lineageTag: 63bdb1cd-7f08-480e-a6e5-cbbf3326eceb

	column 'p.P3M1Selection (copy)_1429611422904180762'
		dataType: string
		summarizeBy: none
		sourceColumn: p.P3M1Selection (copy)_1429611422904180762
		lineageTag: f0749a29-1462-49a7-89e7-1262d0d5503b

	column 'p.P3M2Selection (copy)_1429611422904180763'
		dataType: string
		summarizeBy: none
		sourceColumn: p.P3M2Selection (copy)_1429611422904180763
		lineageTag: a9c45cee-7f4c-4454-a1b9-49fe93c73eea

	column 'p.P3M3Selection (copy)_1429611422904180764'
		dataType: string
		summarizeBy: none
		sourceColumn: p.P3M3Selection (copy)_1429611422904180764
		lineageTag: 0a75716a-58b0-44a1-89fb-a87c6bb3661d

	column 'p.Pillar1 (copy) (copy) (copy) (copy) (copy)_1101693074698227730'
		dataType: double
		summarizeBy: sum
		sourceColumn: p.Pillar1 (copy) (copy) (copy) (copy) (copy)_1101693074698227730
		lineageTag: e387366c-934f-40e6-8606-1c362fd1d7e6

	column 'p.Pillar1 (copy) (copy) (copy) (copy)_1101693074698219537'
		dataType: double
		summarizeBy: sum
		sourceColumn: p.Pillar1 (copy) (copy) (copy) (copy)_1101693074698219537
		lineageTag: 46279970-e28d-4a18-b5c4-978a7cb1dd7d

	column 'p.Pillar1 (copy) (copy) (copy)_1101693074698211344'
		dataType: double
		summarizeBy: sum
		sourceColumn: p.Pillar1 (copy) (copy) (copy)_1101693074698211344
		lineageTag: 54a7af02-0cbd-469f-8410-23b9b88e7262

	column 'p.Pillar1 (copy) (copy)_1101693074698203151'
		dataType: double
		summarizeBy: sum
		sourceColumn: p.Pillar1 (copy) (copy)_1101693074698203151
		lineageTag: eaee8f3a-2a94-4721-850c-db891ad466ca

	column 'p.Pillar1 (copy)_1101693074698190862'
		dataType: double
		summarizeBy: sum
		sourceColumn: p.Pillar1 (copy)_1101693074698190862
		lineageTag: a5822ca9-21f1-4f64-bc35-cd6596ea3758

	partition FullData = m
		mode: import
		source =
			let
				Direct1 = "C:\Users\Pooja Satija\Downloads\tab-pbip-31-code-new-visuals\tab-pbip-31-code-new-visuals\ExecutiveKPITest\Data\HyperExports\Metric Lookup (Metric List).csv",
				Direct2 = "C:\Users\dhrsharm\Downloads\tab-pbip-31\ExecutiveKPITest\Data\HyperExports\Metric Lookup (Metric List).csv",
				Direct3 = "C:\Users\dhrsharm\Downloads\ExecutiveKPITest\Data\HyperExports\Metric Lookup (Metric List).csv",
				Source = try Csv.Document(File.Contents(Direct1), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None])
					otherwise try Csv.Document(File.Contents(Direct2), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None])
					otherwise try Csv.Document(File.Contents(Direct3), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None])
					otherwise
						let
							Found = try Table.First(Table.SelectRows(Folder.Files("C:\Users\Pooja Satija\Downloads"), each [Name] = "Metric Lookup (Metric List).csv")) otherwise null,
							Path = if Found = null then error "Metric Lookup CSV not found under Downloads" else Found[Folder Path] & Found[Name]
						in
							Csv.Document(File.Contents(Path), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
			in
				Promoted
	annotation PBI_ResultType = Table

